// GERADO por scripts/create-ghl-coupons.mjs — não editar à mão.
import type { Coupon } from "./coupons";

export const GHL_COUPONS: Coupon[] = [
  { company: "3 T Financial Solution", code: "3tfinancialsoluqufstarter", note: "Plano Starter" },
  { company: "3 T Financial Solution", code: "3tfinancialsolutiongrowth", note: "Plano Growth" },
  { company: "3 T Financial Solution", code: "3tfinancialsolutionagency", note: "Plano Agency" },
  { company: "3t", code: "3tstarter", note: "Plano Starter" },
  { company: "3t", code: "3tgrowth", note: "Plano Growth" },
  { company: "3t", code: "3tagency", note: "Plano Agency" },
  { company: "3T Financial General Account", code: "3tfinancialgene7nqstarter", note: "Plano Starter" },
  { company: "3T Financial General Account", code: "3tfinancialgener7nqgrowth", note: "Plano Growth" },
  { company: "3T Financial General Account", code: "3tfinancialgener7nqagency", note: "Plano Agency" },
  { company: "3t Financial Group", code: "3tfinancialgroupstarter", note: "Plano Starter" },
  { company: "3t Financial Group", code: "3tfinancialgroupgrowth", note: "Plano Growth" },
  { company: "3t Financial Group", code: "3tfinancialgroupagency", note: "Plano Agency" },
  { company: "5 Rings", code: "5ringsstarter", note: "Plano Starter" },
  { company: "5 Rings", code: "5ringsgrowth", note: "Plano Growth" },
  { company: "5 Rings", code: "5ringsagency", note: "Plano Agency" },
  { company: "A Forja Financial", code: "aforjafinancialstarter", note: "Plano Starter" },
  { company: "A Forja Financial", code: "aforjafinancialgrowth", note: "Plano Growth" },
  { company: "A Forja Financial", code: "aforjafinancialagency", note: "Plano Agency" },
  { company: "Absoluto", code: "absolutostarter", note: "Plano Starter" },
  { company: "Absoluto", code: "absolutogrowth", note: "Plano Growth" },
  { company: "Absoluto", code: "absolutoagency", note: "Plano Agency" },
  { company: "Ademo Financial Group", code: "ademofinancialg1gnstarter", note: "Plano Starter" },
  { company: "Ademo Financial Group", code: "ademofinancialgroupgrowth", note: "Plano Growth" },
  { company: "Ademo Financial Group", code: "ademofinancialgroupagency", note: "Plano Agency" },
  { company: "Adriano Buzolin Cruz", code: "adrianobuzolincruzstarter", note: "Plano Starter" },
  { company: "Adriano Buzolin Cruz", code: "adrianobuzolincruzgrowth", note: "Plano Growth" },
  { company: "Adriano Buzolin Cruz", code: "adrianobuzolincruzagency", note: "Plano Agency" },
  { company: "Agency Over Wan", code: "agencyoverwanstarter", note: "Plano Starter" },
  { company: "Agency Over Wan", code: "agencyoverwangrowth", note: "Plano Growth" },
  { company: "Agency Over Wan", code: "agencyoverwanagency", note: "Plano Agency" },
  { company: "Agency Snapshot Clean Master v1", code: "agencysnapshotcrcjstarter", note: "Plano Starter" },
  { company: "Agency Snapshot Clean Master v1", code: "agencysnapshotclrcjgrowth", note: "Plano Growth" },
  { company: "Agency Snapshot Clean Master v1", code: "agencysnapshotclrcjagency", note: "Plano Agency" },
  { company: "Agente Financeiro", code: "agentefinanceirostarter", note: "Plano Starter" },
  { company: "Agente Financeiro", code: "agentefinanceirogrowth", note: "Plano Growth" },
  { company: "Agente Financeiro", code: "agentefinanceiroagency", note: "Plano Agency" },
  { company: "AI Chat Creation", code: "aichatcreationstarter", note: "Plano Starter" },
  { company: "AI Chat Creation", code: "aichatcreationgrowth", note: "Plano Growth" },
  { company: "AI Chat Creation", code: "aichatcreationagency", note: "Plano Agency" },
  { company: "Airam Da Silva", code: "airamdasilvastarter", note: "Plano Starter" },
  { company: "Airam Da Silva", code: "airamdasilvagrowth", note: "Plano Growth" },
  { company: "Airam Da Silva", code: "airamdasilvaagency", note: "Plano Agency" },
  { company: "Alaska Tech Store", code: "alaskatechstorestarter", note: "Plano Starter" },
  { company: "Alaska Tech Store", code: "alaskatechstoregrowth", note: "Plano Growth" },
  { company: "Alaska Tech Store", code: "alaskatechstoreagency", note: "Plano Agency" },
  { company: "Aleteia", code: "aleteiastarter", note: "Plano Starter" },
  { company: "Aleteia", code: "aleteiagrowth", note: "Plano Growth" },
  { company: "Aleteia", code: "aleteiaagency", note: "Plano Agency" },
  { company: "Alive", code: "alivestarter", note: "Plano Starter" },
  { company: "Alive", code: "alivegrowth", note: "Plano Growth" },
  { company: "Alive", code: "aliveagency", note: "Plano Agency" },
  { company: "All In Financial", code: "allinfinancialstarter", note: "Plano Starter" },
  { company: "All In Financial", code: "allinfinancialgrowth", note: "Plano Growth" },
  { company: "All In Financial", code: "allinfinancialagency", note: "Plano Agency" },
  { company: "AllBridge Solutions", code: "allbridgesolutionsstarter", note: "Plano Starter" },
  { company: "AllBridge Solutions", code: "allbridgesolutionsgrowth", note: "Plano Growth" },
  { company: "AllBridge Solutions", code: "allbridgesolutionsagency", note: "Plano Agency" },
  { company: "Allure Capital", code: "allurecapitalstarter", note: "Plano Starter" },
  { company: "Allure Capital", code: "allurecapitalgrowth", note: "Plano Growth" },
  { company: "Allure Capital", code: "allurecapitalagency", note: "Plano Agency" },
  { company: "Alves Cury Clients", code: "alvescuryclientsstarter", note: "Plano Starter" },
  { company: "Alves Cury Clients", code: "alvescuryclientsgrowth", note: "Plano Growth" },
  { company: "Alves Cury Clients", code: "alvescuryclientsagency", note: "Plano Agency" },
  { company: "Alves Cury Financial", code: "alvescuryfinancialstarter", note: "Plano Starter" },
  { company: "Alves Cury Financial", code: "alvescuryfinancialgrowth", note: "Plano Growth" },
  { company: "Alves Cury Financial", code: "alvescuryfinancialagency", note: "Plano Agency" },
  { company: "Ana Carvalho", code: "anacarvalhostarter", note: "Plano Starter" },
  { company: "Ana Carvalho", code: "anacarvalhogrowth", note: "Plano Growth" },
  { company: "Ana Carvalho", code: "anacarvalhoagency", note: "Plano Agency" },
  { company: "Ana Paula Lemika", code: "anapaulalemikastarter", note: "Plano Starter" },
  { company: "Ana Paula Lemika", code: "anapaulalemikagrowth", note: "Plano Growth" },
  { company: "Ana Paula Lemika", code: "anapaulalemikaagency", note: "Plano Agency" },
  { company: "Ana Paula Rangel", code: "anapaularangelstarter", note: "Plano Starter" },
  { company: "Ana Paula Rangel", code: "anapaularangelgrowth", note: "Plano Growth" },
  { company: "Ana Paula Rangel", code: "anapaularangelagency", note: "Plano Agency" },
  { company: "Ana Sendir", code: "anasendirstarter", note: "Plano Starter" },
  { company: "Ana Sendir", code: "anasendirgrowth", note: "Plano Growth" },
  { company: "Ana Sendir", code: "anasendiragency", note: "Plano Agency" },
  { company: "Anderson Mendes de Carvalho's Account", code: "andersonmendesd1ixstarter", note: "Plano Starter" },
  { company: "Anderson Mendes de Carvalho's Account", code: "andersonmendesde1ixgrowth", note: "Plano Growth" },
  { company: "Anderson Mendes de Carvalho's Account", code: "andersonmendesde1ixagency", note: "Plano Agency" },
  { company: "Andreza Cordutsky", code: "andrezacordutskystarter", note: "Plano Starter" },
  { company: "Andreza Cordutsky", code: "andrezacordutskygrowth", note: "Plano Growth" },
  { company: "Andreza Cordutsky", code: "andrezacordutskyagency", note: "Plano Agency" },
  { company: "Andréia Carreiro", code: "andreiacarreirostarter", note: "Plano Starter" },
  { company: "Andréia Carreiro", code: "andreiacarreirogrowth", note: "Plano Growth" },
  { company: "Andréia Carreiro", code: "andreiacarreiroagency", note: "Plano Agency" },
  { company: "ANTONIO RAMPAZZO", code: "antoniorampazzostarter", note: "Plano Starter" },
  { company: "ANTONIO RAMPAZZO", code: "antoniorampazzogrowth", note: "Plano Growth" },
  { company: "ANTONIO RAMPAZZO", code: "antoniorampazzoagency", note: "Plano Agency" },
  { company: "Ariane", code: "arianestarter", note: "Plano Starter" },
  { company: "Ariane", code: "arianegrowth", note: "Plano Growth" },
  { company: "Ariane", code: "arianeagency", note: "Plano Agency" },
  { company: "Ark Financial", code: "arkfinancialstarter", note: "Plano Starter" },
  { company: "Ark Financial", code: "arkfinancialgrowth", note: "Plano Growth" },
  { company: "Ark Financial", code: "arkfinancialagency", note: "Plano Agency" },
  { company: "Ashyley Cardoso", code: "ashyleycardosostarter", note: "Plano Starter" },
  { company: "Ashyley Cardoso", code: "ashyleycardosogrowth", note: "Plano Growth" },
  { company: "Ashyley Cardoso", code: "ashyleycardosoagency", note: "Plano Agency" },
  { company: "Bautz Life Insurance", code: "bautzlifeinsurancestarter", note: "Plano Starter" },
  { company: "Bautz Life Insurance", code: "bautzlifeinsurancegrowth", note: "Plano Growth" },
  { company: "Bautz Life Insurance", code: "bautzlifeinsuranceagency", note: "Plano Agency" },
  { company: "Bella Luna Llc", code: "bellalunallcstarter", note: "Plano Starter" },
  { company: "Bella Luna Llc", code: "bellalunallcgrowth", note: "Plano Growth" },
  { company: "Bella Luna Llc", code: "bellalunallcagency", note: "Plano Agency" },
  { company: "Better Life Financial", code: "betterlifefinanm5zstarter", note: "Plano Starter" },
  { company: "Better Life Financial", code: "betterlifefinancialgrowth", note: "Plano Growth" },
  { company: "Better Life Financial", code: "betterlifefinancialagency", note: "Plano Agency" },
  { company: "Bia Prado", code: "biapradostarter", note: "Plano Starter" },
  { company: "Bia Prado", code: "biapradogrowth", note: "Plano Growth" },
  { company: "Bia Prado", code: "biapradoagency", note: "Plano Agency" },
  { company: "Bianca Broglio", code: "biancabrogliostarter", note: "Plano Starter" },
  { company: "Bianca Broglio", code: "biancabrogliogrowth", note: "Plano Growth" },
  { company: "Bianca Broglio", code: "biancabroglioagency", note: "Plano Agency" },
  { company: "Bigagency Finance Specialists", code: "bigagencyfinanc71istarter", note: "Plano Starter" },
  { company: "Bigagency Finance Specialists", code: "bigagencyfinance71igrowth", note: "Plano Growth" },
  { company: "Bigagency Finance Specialists", code: "bigagencyfinance71iagency", note: "Plano Agency" },
  { company: "Black F", code: "blackfstarter", note: "Plano Starter" },
  { company: "Black F", code: "blackfgrowth", note: "Plano Growth" },
  { company: "Black F", code: "blackfagency", note: "Plano Agency" },
  { company: "Black Financial Freedom", code: "blackfinancialfbynstarter", note: "Plano Starter" },
  { company: "Black Financial Freedom", code: "blackfinancialfrbyngrowth", note: "Plano Growth" },
  { company: "Black Financial Freedom", code: "blackfinancialfrbynagency", note: "Plano Agency" },
  { company: "Br Usa Business", code: "brusabusinessstarter", note: "Plano Starter" },
  { company: "Br Usa Business", code: "brusabusinessgrowth", note: "Plano Growth" },
  { company: "Br Usa Business", code: "brusabusinessagency", note: "Plano Agency" },
  { company: "Braga-Lett Financial", code: "bragalettfinancialstarter", note: "Plano Starter" },
  { company: "Braga-Lett Financial", code: "bragalettfinancialgrowth", note: "Plano Growth" },
  { company: "Braga-Lett Financial", code: "bragalettfinancialagency", note: "Plano Agency" },
  { company: "Buba Rufino", code: "bubarufinostarter", note: "Plano Starter" },
  { company: "Buba Rufino", code: "bubarufinogrowth", note: "Plano Growth" },
  { company: "Buba Rufino", code: "bubarufinoagency", note: "Plano Agency" },
  { company: "by Mertz", code: "bymertzstarter", note: "Plano Starter" },
  { company: "by Mertz", code: "bymertzgrowth", note: "Plano Growth" },
  { company: "by Mertz", code: "bymertzagency", note: "Plano Agency" },
  { company: "Carla Konno", code: "carlakonnostarter", note: "Plano Starter" },
  { company: "Carla Konno", code: "carlakonnogrowth", note: "Plano Growth" },
  { company: "Carla Konno", code: "carlakonnoagency", note: "Plano Agency" },
  { company: "Carolina Cabellos", code: "carolinacabellosstarter", note: "Plano Starter" },
  { company: "Carolina Cabellos", code: "carolinacabellosgrowth", note: "Plano Growth" },
  { company: "Carolina Cabellos", code: "carolinacabellosagency", note: "Plano Agency" },
  { company: "Caroline Alexandre Da Silva's Account", code: "carolinealexandkg3starter", note: "Plano Starter" },
  { company: "Caroline Alexandre Da Silva's Account", code: "carolinealexandrkg3growth", note: "Plano Growth" },
  { company: "Caroline Alexandre Da Silva's Account", code: "carolinealexandrkg3agency", note: "Plano Agency" },
  { company: "Casa Do Poder", code: "casadopoderstarter", note: "Plano Starter" },
  { company: "Casa Do Poder", code: "casadopodergrowth", note: "Plano Growth" },
  { company: "Casa Do Poder", code: "casadopoderagency", note: "Plano Agency" },
  { company: "Cbc Financial Solutions", code: "cbcfinancialsoljqwstarter", note: "Plano Starter" },
  { company: "Cbc Financial Solutions", code: "cbcfinancialsolujqwgrowth", note: "Plano Growth" },
  { company: "Cbc Financial Solutions", code: "cbcfinancialsolujqwagency", note: "Plano Agency" },
  { company: "Charles Dantas's Account", code: "charlesdantassa14tstarter", note: "Plano Starter" },
  { company: "Charles Dantas's Account", code: "charlesdantassac14tgrowth", note: "Plano Growth" },
  { company: "Charles Dantas's Account", code: "charlesdantassac14tagency", note: "Plano Agency" },
  { company: "Claudia Fehribach", code: "claudiafehribachstarter", note: "Plano Starter" },
  { company: "Claudia Fehribach", code: "claudiafehribachgrowth", note: "Plano Growth" },
  { company: "Claudia Fehribach", code: "claudiafehribachagency", note: "Plano Agency" },
  { company: "Claudio Santos's Account", code: "claudiosantossal5vstarter", note: "Plano Starter" },
  { company: "Claudio Santos's Account", code: "claudiosantossacl5vgrowth", note: "Plano Growth" },
  { company: "Claudio Santos's Account", code: "claudiosantossacl5vagency", note: "Plano Agency" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "cmfinancialsolujzxstarter", note: "Plano Starter" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "cmfinancialsolutjzxgrowth", note: "Plano Growth" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "cmfinancialsolutjzxagency", note: "Plano Agency" },
  { company: "Coiro Finances", code: "coirofinancesstarter", note: "Plano Starter" },
  { company: "Coiro Finances", code: "coirofinancesgrowth", note: "Plano Growth" },
  { company: "Coiro Finances", code: "coirofinancesagency", note: "Plano Agency" },
  { company: "Construction Connection", code: "constructioncon106starter", note: "Plano Starter" },
  { company: "Construction Connection", code: "constructionconn106growth", note: "Plano Growth" },
  { company: "Construction Connection", code: "constructionconn106agency", note: "Plano Agency" },
  { company: "CROSS Alliance Agency", code: "crossallianceag19gstarter", note: "Plano Starter" },
  { company: "CROSS Alliance Agency", code: "crossallianceagencygrowth", note: "Plano Growth" },
  { company: "CROSS Alliance Agency", code: "crossallianceagencyagency", note: "Plano Agency" },
  { company: "Cynthia Avelar", code: "cynthiaavelarstarter", note: "Plano Starter" },
  { company: "Cynthia Avelar", code: "cynthiaavelargrowth", note: "Plano Growth" },
  { company: "Cynthia Avelar", code: "cynthiaavelaragency", note: "Plano Agency" },
  { company: "Cynthia Avelar's Account", code: "cynthiaavelarsa1p6starter", note: "Plano Starter" },
  { company: "Cynthia Avelar's Account", code: "cynthiaavelarsac1p6growth", note: "Plano Growth" },
  { company: "Cynthia Avelar's Account", code: "cynthiaavelarsac1p6agency", note: "Plano Agency" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "dgoncalvesmontewwgstarter", note: "Plano Starter" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "dgoncalvesmonteiwwggrowth", note: "Plano Growth" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "dgoncalvesmonteiwwgagency", note: "Plano Agency" },
  { company: "D&M Financial", code: "dmfinancialstarter", note: "Plano Starter" },
  { company: "D&M Financial", code: "dmfinancialgrowth", note: "Plano Growth" },
  { company: "D&M Financial", code: "dmfinancialagency", note: "Plano Agency" },
  { company: "Daniely Jones", code: "danielyjonesstarter", note: "Plano Starter" },
  { company: "Daniely Jones", code: "danielyjonesgrowth", note: "Plano Growth" },
  { company: "Daniely Jones", code: "danielyjonesagency", note: "Plano Agency" },
  { company: "Dannyele", code: "dannyelestarter", note: "Plano Starter" },
  { company: "Dannyele", code: "dannyelegrowth", note: "Plano Growth" },
  { company: "Dannyele", code: "dannyeleagency", note: "Plano Agency" },
  { company: "Dina Souza", code: "dinasouzastarter", note: "Plano Starter" },
  { company: "Dina Souza", code: "dinasouzagrowth", note: "Plano Growth" },
  { company: "Dina Souza", code: "dinasouzaagency", note: "Plano Agency" },
  { company: "Djessica Bocardi", code: "djessicabocardistarter", note: "Plano Starter" },
  { company: "Djessica Bocardi", code: "djessicabocardigrowth", note: "Plano Growth" },
  { company: "Djessica Bocardi", code: "djessicabocardiagency", note: "Plano Agency" },
  { company: "Douglas E Thaiana", code: "douglasethaianastarter", note: "Plano Starter" },
  { company: "Douglas E Thaiana", code: "douglasethaianagrowth", note: "Plano Growth" },
  { company: "Douglas E Thaiana", code: "douglasethaianaagency", note: "Plano Agency" },
  { company: "Dream Makers Financial", code: "dreammakersfina1rbstarter", note: "Plano Starter" },
  { company: "Dream Makers Financial", code: "dreammakersfinan1rbgrowth", note: "Plano Growth" },
  { company: "Dream Makers Financial", code: "dreammakersfinan1rbagency", note: "Plano Agency" },
  { company: "Dream Team - Fernando & Ellyn", code: "dreamteamfernanslqstarter", note: "Plano Starter" },
  { company: "Dream Team - Fernando & Ellyn", code: "dreamteamfernandslqgrowth", note: "Plano Growth" },
  { company: "Dream Team - Fernando & Ellyn", code: "dreamteamfernandslqagency", note: "Plano Agency" },
  { company: "Dreamers Financial", code: "dreamersfinancialstarter", note: "Plano Starter" },
  { company: "Dreamers Financial", code: "dreamersfinancialgrowth", note: "Plano Growth" },
  { company: "Dreamers Financial", code: "dreamersfinancialagency", note: "Plano Agency" },
  { company: "Drive ON Autos", code: "driveonautosstarter", note: "Plano Starter" },
  { company: "Drive ON Autos", code: "driveonautosgrowth", note: "Plano Growth" },
  { company: "Drive ON Autos", code: "driveonautosagency", note: "Plano Agency" },
  { company: "Drive ON Subscriptions", code: "driveonsubscripo8astarter", note: "Plano Starter" },
  { company: "Drive ON Subscriptions", code: "driveonsubscripto8agrowth", note: "Plano Growth" },
  { company: "Drive ON Subscriptions", code: "driveonsubscripto8aagency", note: "Plano Agency" },
  { company: "DTLBiz", code: "dtlbizstarter", note: "Plano Starter" },
  { company: "DTLBiz", code: "dtlbizgrowth", note: "Plano Growth" },
  { company: "DTLBiz", code: "dtlbizagency", note: "Plano Agency" },
  { company: "e-Z Accounting Services Inc", code: "ezaccountingserog5starter", note: "Plano Starter" },
  { company: "e-Z Accounting Services Inc", code: "ezaccountingservog5growth", note: "Plano Growth" },
  { company: "e-Z Accounting Services Inc", code: "ezaccountingservog5agency", note: "Plano Agency" },
  { company: "Elevated Wealth", code: "elevatedwealthstarter", note: "Plano Starter" },
  { company: "Elevated Wealth", code: "elevatedwealthgrowth", note: "Plano Growth" },
  { company: "Elevated Wealth", code: "elevatedwealthagency", note: "Plano Agency" },
  { company: "Eliane de Souza", code: "elianedesouzastarter", note: "Plano Starter" },
  { company: "Eliane de Souza", code: "elianedesouzagrowth", note: "Plano Growth" },
  { company: "Eliane de Souza", code: "elianedesouzaagency", note: "Plano Agency" },
  { company: "Eliane Melo", code: "elianemelostarter", note: "Plano Starter" },
  { company: "Eliane Melo", code: "elianemelogrowth", note: "Plano Growth" },
  { company: "Eliane Melo", code: "elianemeloagency", note: "Plano Agency" },
  { company: "ELITE FINANCIAL", code: "elitefinancialstarter", note: "Plano Starter" },
  { company: "ELITE FINANCIAL", code: "elitefinancialgrowth", note: "Plano Growth" },
  { company: "ELITE FINANCIAL", code: "elitefinancialagency", note: "Plano Agency" },
  { company: "Espaço Se Conecte", code: "espacoseconectestarter", note: "Plano Starter" },
  { company: "Espaço Se Conecte", code: "espacoseconectegrowth", note: "Plano Growth" },
  { company: "Espaço Se Conecte", code: "espacoseconecteagency", note: "Plano Agency" },
  { company: "EverRise Co.", code: "everrisecostarter", note: "Plano Starter" },
  { company: "EverRise Co.", code: "everrisecogrowth", note: "Plano Growth" },
  { company: "EverRise Co.", code: "everrisecoagency", note: "Plano Agency" },
  { company: "EverSafe Life Solutions", code: "eversafelifesol1smstarter", note: "Plano Starter" },
  { company: "EverSafe Life Solutions", code: "eversafelifesolu1smgrowth", note: "Plano Growth" },
  { company: "EverSafe Life Solutions", code: "eversafelifesolu1smagency", note: "Plano Agency" },
  { company: "Face Beauty", code: "facebeautystarter", note: "Plano Starter" },
  { company: "Face Beauty", code: "facebeautygrowth", note: "Plano Growth" },
  { company: "Face Beauty", code: "facebeautyagency", note: "Plano Agency" },
  { company: "Fad Financial Solutions", code: "fadfinancialsol8lvstarter", note: "Plano Starter" },
  { company: "Fad Financial Solutions", code: "fadfinancialsolu8lvgrowth", note: "Plano Growth" },
  { company: "Fad Financial Solutions", code: "fadfinancialsolu8lvagency", note: "Plano Agency" },
  { company: "Fernanda Pontoni", code: "fernandapontonistarter", note: "Plano Starter" },
  { company: "Fernanda Pontoni", code: "fernandapontonigrowth", note: "Plano Growth" },
  { company: "Fernanda Pontoni", code: "fernandapontoniagency", note: "Plano Agency" },
  { company: "Financial Peace Usa", code: "financialpeaceusastarter", note: "Plano Starter" },
  { company: "Financial Peace Usa", code: "financialpeaceusagrowth", note: "Plano Growth" },
  { company: "Financial Peace Usa", code: "financialpeaceusaagency", note: "Plano Agency" },
  { company: "Financial Star", code: "financialstarstarter", note: "Plano Starter" },
  { company: "Financial Star", code: "financialstargrowth", note: "Plano Growth" },
  { company: "Financial Star", code: "financialstaragency", note: "Plano Agency" },
  { company: "Finexpress Mortgage", code: "finexpressmortgagestarter", note: "Plano Starter" },
  { company: "Finexpress Mortgage", code: "finexpressmortgagegrowth", note: "Plano Growth" },
  { company: "Finexpress Mortgage", code: "finexpressmortgageagency", note: "Plano Agency" },
  { company: "Fire Financial", code: "firefinancialstarter", note: "Plano Starter" },
  { company: "Fire Financial", code: "firefinancialgrowth", note: "Plano Growth" },
  { company: "Fire Financial", code: "firefinancialagency", note: "Plano Agency" },
  { company: "First Class Financial", code: "firstclassfinanbbxstarter", note: "Plano Starter" },
  { company: "First Class Financial", code: "firstclassfinancialgrowth", note: "Plano Growth" },
  { company: "First Class Financial", code: "firstclassfinancialagency", note: "Plano Agency" },
  { company: "Five Rings", code: "fiveringsstarter", note: "Plano Starter" },
  { company: "Five Rings", code: "fiveringsgrowth", note: "Plano Growth" },
  { company: "Five Rings", code: "fiveringsagency", note: "Plano Agency" },
  { company: "Five Star Ricos", code: "fivestarricosstarter", note: "Plano Starter" },
  { company: "Five Star Ricos", code: "fivestarricosgrowth", note: "Plano Growth" },
  { company: "Five Star Ricos", code: "fivestarricosagency", note: "Plano Agency" },
  { company: "FK Business Advice LLC", code: "fkbusinessadvic1arstarter", note: "Plano Starter" },
  { company: "FK Business Advice LLC", code: "fkbusinessadvicellcgrowth", note: "Plano Growth" },
  { company: "FK Business Advice LLC", code: "fkbusinessadvicellcagency", note: "Plano Agency" },
  { company: "Flavi Sant Anna", code: "flavisantannastarter", note: "Plano Starter" },
  { company: "Flavi Sant Anna", code: "flavisantannagrowth", note: "Plano Growth" },
  { company: "Flavi Sant Anna", code: "flavisantannaagency", note: "Plano Agency" },
  { company: "Gabriel Ximenez's Account", code: "gabrielximenezsrswstarter", note: "Plano Starter" },
  { company: "Gabriel Ximenez's Account", code: "gabrielximenezsarswgrowth", note: "Plano Growth" },
  { company: "Gabriel Ximenez's Account", code: "gabrielximenezsarswagency", note: "Plano Agency" },
  { company: "Gilmara", code: "gilmarastarter", note: "Plano Starter" },
  { company: "Gilmara", code: "gilmaragrowth", note: "Plano Growth" },
  { company: "Gilmara", code: "gilmaraagency", note: "Plano Agency" },
  { company: "Growth Snapshot", code: "growthsnapshotstarter", note: "Plano Starter" },
  { company: "Growth Snapshot", code: "growthsnapshotgrowth", note: "Plano Growth" },
  { company: "Growth Snapshot", code: "growthsnapshotagency", note: "Plano Agency" },
  { company: "Growth Snapshot Clean Master v1", code: "growthsnapshotc12mstarter", note: "Plano Starter" },
  { company: "Growth Snapshot Clean Master v1", code: "growthsnapshotcl12mgrowth", note: "Plano Growth" },
  { company: "Growth Snapshot Clean Master v1", code: "growthsnapshotcl12magency", note: "Plano Agency" },
  { company: "Guilherme Lappe", code: "guilhermelappestarter", note: "Plano Starter" },
  { company: "Guilherme Lappe", code: "guilhermelappegrowth", note: "Plano Growth" },
  { company: "Guilherme Lappe", code: "guilhermelappeagency", note: "Plano Agency" },
  { company: "Gustavo Couto's Account", code: "gustavocoutosac8utstarter", note: "Plano Starter" },
  { company: "Gustavo Couto's Account", code: "gustavocoutosacc8utgrowth", note: "Plano Growth" },
  { company: "Gustavo Couto's Account", code: "gustavocoutosacc8utagency", note: "Plano Agency" },
  { company: "Haven Solutions", code: "havensolutionsstarter", note: "Plano Starter" },
  { company: "Haven Solutions", code: "havensolutionsgrowth", note: "Plano Growth" },
  { company: "Haven Solutions", code: "havensolutionsagency", note: "Plano Agency" },
  { company: "HELTON LEAL CARDOSO", code: "heltonlealcardosostarter", note: "Plano Starter" },
  { company: "HELTON LEAL CARDOSO", code: "heltonlealcardosogrowth", note: "Plano Growth" },
  { company: "HELTON LEAL CARDOSO", code: "heltonlealcardosoagency", note: "Plano Agency" },
  { company: "Heritage Group", code: "heritagegroupstarter", note: "Plano Starter" },
  { company: "Heritage Group", code: "heritagegroupgrowth", note: "Plano Growth" },
  { company: "Heritage Group", code: "heritagegroupagency", note: "Plano Agency" },
  { company: "High Up Financial", code: "highupfinancialstarter", note: "Plano Starter" },
  { company: "High Up Financial", code: "highupfinancialgrowth", note: "Plano Growth" },
  { company: "High Up Financial", code: "highupfinancialagency", note: "Plano Agency" },
  { company: "Hope Financial Solutions", code: "hopefinancialsoabmstarter", note: "Plano Starter" },
  { company: "Hope Financial Solutions", code: "hopefinancialsolabmgrowth", note: "Plano Growth" },
  { company: "Hope Financial Solutions", code: "hopefinancialsolabmagency", note: "Plano Agency" },
  { company: "Ideal Business School", code: "idealbusinessscmc3starter", note: "Plano Starter" },
  { company: "Ideal Business School", code: "idealbusinessschoolgrowth", note: "Plano Growth" },
  { company: "Ideal Business School", code: "idealbusinessschoolagency", note: "Plano Agency" },
  { company: "Ideal English School", code: "idealenglishschoolstarter", note: "Plano Starter" },
  { company: "Ideal English School", code: "idealenglishschoolgrowth", note: "Plano Growth" },
  { company: "Ideal English School", code: "idealenglishschoolagency", note: "Plano Agency" },
  { company: "IGNORE", code: "ignorestarter", note: "Plano Starter" },
  { company: "IGNORE", code: "ignoregrowth", note: "Plano Growth" },
  { company: "IGNORE", code: "ignoreagency", note: "Plano Agency" },
  { company: "IMC Realty Group", code: "imcrealtygroupstarter", note: "Plano Starter" },
  { company: "IMC Realty Group", code: "imcrealtygroupgrowth", note: "Plano Growth" },
  { company: "IMC Realty Group", code: "imcrealtygroupagency", note: "Plano Agency" },
  { company: "Imperium Life Protection", code: "imperiumlifepro1qestarter", note: "Plano Starter" },
  { company: "Imperium Life Protection", code: "imperiumlifeprot1qegrowth", note: "Plano Growth" },
  { company: "Imperium Life Protection", code: "imperiumlifeprot1qeagency", note: "Plano Agency" },
  { company: "Ingrid Andre", code: "ingridandrestarter", note: "Plano Starter" },
  { company: "Ingrid Andre", code: "ingridandregrowth", note: "Plano Growth" },
  { company: "Ingrid Andre", code: "ingridandreagency", note: "Plano Agency" },
  { company: "Insurance Snapshot", code: "insurancesnapshotstarter", note: "Plano Starter" },
  { company: "Insurance Snapshot", code: "insurancesnapshotgrowth", note: "Plano Growth" },
  { company: "Insurance Snapshot", code: "insurancesnapshotagency", note: "Plano Agency" },
  { company: "Iory Silva", code: "iorysilvastarter", note: "Plano Starter" },
  { company: "Iory Silva", code: "iorysilvagrowth", note: "Plano Growth" },
  { company: "Iory Silva", code: "iorysilvaagency", note: "Plano Agency" },
  { company: "Jaqueline Schoenrock", code: "jaquelineschoen1n3starter", note: "Plano Starter" },
  { company: "Jaqueline Schoenrock", code: "jaquelineschoenrockgrowth", note: "Plano Growth" },
  { company: "Jaqueline Schoenrock", code: "jaquelineschoenrockagency", note: "Plano Agency" },
  { company: "Jeane Thorpe", code: "jeanethorpestarter", note: "Plano Starter" },
  { company: "Jeane Thorpe", code: "jeanethorpegrowth", note: "Plano Growth" },
  { company: "Jeane Thorpe", code: "jeanethorpeagency", note: "Plano Agency" },
  { company: "JL Financial Strategies", code: "jlfinancialstrasdustarter", note: "Plano Starter" },
  { company: "JL Financial Strategies", code: "jlfinancialstratsdugrowth", note: "Plano Growth" },
  { company: "JL Financial Strategies", code: "jlfinancialstratsduagency", note: "Plano Agency" },
  { company: "John David", code: "johndavidstarter", note: "Plano Starter" },
  { company: "John David", code: "johndavidgrowth", note: "Plano Growth" },
  { company: "John David", code: "johndavidagency", note: "Plano Agency" },
  { company: "John Langley", code: "johnlangleystarter", note: "Plano Starter" },
  { company: "John Langley", code: "johnlangleygrowth", note: "Plano Growth" },
  { company: "John Langley", code: "johnlangleyagency", note: "Plano Agency" },
  { company: "Jonathan Duque", code: "jonathanduquestarter", note: "Plano Starter" },
  { company: "Jonathan Duque", code: "jonathanduquegrowth", note: "Plano Growth" },
  { company: "Jonathan Duque", code: "jonathanduqueagency", note: "Plano Agency" },
  { company: "Ju E Lari", code: "juelaristarter", note: "Plano Starter" },
  { company: "Ju E Lari", code: "juelarigrowth", note: "Plano Growth" },
  { company: "Ju E Lari", code: "juelariagency", note: "Plano Agency" },
  { company: "Jucelia Batista", code: "juceliabatistastarter", note: "Plano Starter" },
  { company: "Jucelia Batista", code: "juceliabatistagrowth", note: "Plano Growth" },
  { company: "Jucelia Batista", code: "juceliabatistaagency", note: "Plano Agency" },
  { company: "Juliana Pallesi's Account", code: "julianapallesis1ristarter", note: "Plano Starter" },
  { company: "Juliana Pallesi's Account", code: "julianapallesisa1rigrowth", note: "Plano Growth" },
  { company: "Juliana Pallesi's Account", code: "julianapallesisa1riagency", note: "Plano Agency" },
  { company: "Jully Juvencio Saraiva", code: "jullyjuvenciosanzastarter", note: "Plano Starter" },
  { company: "Jully Juvencio Saraiva", code: "jullyjuvenciosarnzagrowth", note: "Plano Growth" },
  { company: "Jully Juvencio Saraiva", code: "jullyjuvenciosarnzaagency", note: "Plano Agency" },
  { company: "K Pires Financial", code: "kpiresfinancialstarter", note: "Plano Starter" },
  { company: "K Pires Financial", code: "kpiresfinancialgrowth", note: "Plano Growth" },
  { company: "K Pires Financial", code: "kpiresfinancialagency", note: "Plano Agency" },
  { company: "Katia Locher", code: "katialocherstarter", note: "Plano Starter" },
  { company: "Katia Locher", code: "katialochergrowth", note: "Plano Growth" },
  { company: "Katia Locher", code: "katialocheragency", note: "Plano Agency" },
  { company: "kellen Silva", code: "kellensilvastarter", note: "Plano Starter" },
  { company: "kellen Silva", code: "kellensilvagrowth", note: "Plano Growth" },
  { company: "kellen Silva", code: "kellensilvaagency", note: "Plano Agency" },
  { company: "Kingdom Financial", code: "kingdomfinancialstarter", note: "Plano Starter" },
  { company: "Kingdom Financial", code: "kingdomfinancialgrowth", note: "Plano Growth" },
  { company: "Kingdom Financial", code: "kingdomfinancialagency", note: "Plano Agency" },
  { company: "Kingdom Sushi", code: "kingdomsushistarter", note: "Plano Starter" },
  { company: "Kingdom Sushi", code: "kingdomsushigrowth", note: "Plano Growth" },
  { company: "Kingdom Sushi", code: "kingdomsushiagency", note: "Plano Agency" },
  { company: "Kingdom Wealth Finance", code: "kingdomwealthfi13tstarter", note: "Plano Starter" },
  { company: "Kingdom Wealth Finance", code: "kingdomwealthfin13tgrowth", note: "Plano Growth" },
  { company: "Kingdom Wealth Finance", code: "kingdomwealthfin13tagency", note: "Plano Agency" },
  { company: "Kore Group", code: "koregroupstarter", note: "Plano Starter" },
  { company: "Kore Group", code: "koregroupgrowth", note: "Plano Growth" },
  { company: "Kore Group", code: "koregroupagency", note: "Plano Agency" },
  { company: "Laiza Estevão", code: "laizaestevaostarter", note: "Plano Starter" },
  { company: "Laiza Estevão", code: "laizaestevaogrowth", note: "Plano Growth" },
  { company: "Laiza Estevão", code: "laizaestevaoagency", note: "Plano Agency" },
  { company: "Lappe Financial Group", code: "lappefinancialg18estarter", note: "Plano Starter" },
  { company: "Lappe Financial Group", code: "lappefinancialgroupgrowth", note: "Plano Growth" },
  { company: "Lappe Financial Group", code: "lappefinancialgroupagency", note: "Plano Agency" },
  { company: "Leandro Pontoni's Account", code: "leandropontonis1c8starter", note: "Plano Starter" },
  { company: "Leandro Pontoni's Account", code: "leandropontonisa1c8growth", note: "Plano Growth" },
  { company: "Leandro Pontoni's Account", code: "leandropontonisa1c8agency", note: "Plano Agency" },
  { company: "Legacy Agency", code: "legacyagencystarter", note: "Plano Starter" },
  { company: "Legacy Agency", code: "legacyagencygrowth", note: "Plano Growth" },
  { company: "Legacy Agency", code: "legacyagencyagency", note: "Plano Agency" },
  { company: "LIBERTY FINANCIAL", code: "libertyfinancialstarter", note: "Plano Starter" },
  { company: "LIBERTY FINANCIAL", code: "libertyfinancialgrowth", note: "Plano Growth" },
  { company: "LIBERTY FINANCIAL", code: "libertyfinancialagency", note: "Plano Agency" },
  { company: "Life Changers", code: "lifechangersstarter", note: "Plano Starter" },
  { company: "Life Changers", code: "lifechangersgrowth", note: "Plano Growth" },
  { company: "Life Changers", code: "lifechangersagency", note: "Plano Agency" },
  { company: "Lifeskeep", code: "lifeskeepstarter", note: "Plano Starter" },
  { company: "Lifeskeep", code: "lifeskeepgrowth", note: "Plano Growth" },
  { company: "Lifeskeep", code: "lifeskeepagency", note: "Plano Agency" },
  { company: "Livia Serpa's Account", code: "liviaserpasaccountstarter", note: "Plano Starter" },
  { company: "Livia Serpa's Account", code: "liviaserpasaccountgrowth", note: "Plano Growth" },
  { company: "Livia Serpa's Account", code: "liviaserpasaccountagency", note: "Plano Agency" },
  { company: "Lucas Bandeira", code: "lucasbandeirastarter", note: "Plano Starter" },
  { company: "Lucas Bandeira", code: "lucasbandeiragrowth", note: "Plano Growth" },
  { company: "Lucas Bandeira", code: "lucasbandeiraagency", note: "Plano Agency" },
  { company: "Lunara Araujo", code: "lunaraaraujostarter", note: "Plano Starter" },
  { company: "Lunara Araujo", code: "lunaraaraujogrowth", note: "Plano Growth" },
  { company: "Lunara Araujo", code: "lunaraaraujoagency", note: "Plano Agency" },
  { company: "Magnet Money", code: "magnetmoneystarter", note: "Plano Starter" },
  { company: "Magnet Money", code: "magnetmoneygrowth", note: "Plano Growth" },
  { company: "Magnet Money", code: "magnetmoneyagency", note: "Plano Agency" },
  { company: "MAGNUM AGENCY", code: "magnumagencystarter", note: "Plano Starter" },
  { company: "MAGNUM AGENCY", code: "magnumagencygrowth", note: "Plano Growth" },
  { company: "MAGNUM AGENCY", code: "magnumagencyagency", note: "Plano Agency" },
  { company: "Manual Call Snapshot", code: "manualcallsnapshotstarter", note: "Plano Starter" },
  { company: "Manual Call Snapshot", code: "manualcallsnapshotgrowth", note: "Plano Growth" },
  { company: "Manual Call Snapshot", code: "manualcallsnapshotagency", note: "Plano Agency" },
  { company: "Manuela Garcia Santos's Account", code: "manuelagarciasarmustarter", note: "Plano Starter" },
  { company: "Manuela Garcia Santos's Account", code: "manuelagarciasanrmugrowth", note: "Plano Growth" },
  { company: "Manuela Garcia Santos's Account", code: "manuelagarciasanrmuagency", note: "Plano Agency" },
  { company: "Marcus Garcia", code: "marcusgarciastarter", note: "Plano Starter" },
  { company: "Marcus Garcia", code: "marcusgarciagrowth", note: "Plano Growth" },
  { company: "Marcus Garcia", code: "marcusgarciaagency", note: "Plano Agency" },
  { company: "Mariana Tambelini", code: "marianatambelinistarter", note: "Plano Starter" },
  { company: "Mariana Tambelini", code: "marianatambelinigrowth", note: "Plano Growth" },
  { company: "Mariana Tambelini", code: "marianatambeliniagency", note: "Plano Agency" },
  { company: "Marina's Personal Account", code: "marinaspersonalnx2starter", note: "Plano Starter" },
  { company: "Marina's Personal Account", code: "marinaspersonalanx2growth", note: "Plano Growth" },
  { company: "Marina's Personal Account", code: "marinaspersonalanx2agency", note: "Plano Agency" },
  { company: "Marina's Support Account", code: "marinassupportaalcstarter", note: "Plano Starter" },
  { company: "Marina's Support Account", code: "marinassupportacalcgrowth", note: "Plano Growth" },
  { company: "Marina's Support Account", code: "marinassupportacalcagency", note: "Plano Agency" },
  { company: "MD GROUP FINANCIAL", code: "mdgroupfinancialstarter", note: "Plano Starter" },
  { company: "MD GROUP FINANCIAL", code: "mdgroupfinancialgrowth", note: "Plano Growth" },
  { company: "MD GROUP FINANCIAL", code: "mdgroupfinancialagency", note: "Plano Agency" },
  { company: "Melina Wiebusch", code: "melinawiebuschstarter", note: "Plano Starter" },
  { company: "Melina Wiebusch", code: "melinawiebuschgrowth", note: "Plano Growth" },
  { company: "Melina Wiebusch", code: "melinawiebuschagency", note: "Plano Agency" },
  { company: "Milionários", code: "milionariosstarter", note: "Plano Starter" },
  { company: "Milionários", code: "milionariosgrowth", note: "Plano Growth" },
  { company: "Milionários", code: "milionariosagency", note: "Plano Agency" },
  { company: "Milton De Abreu's Account", code: "miltondeabreusavvcstarter", note: "Plano Starter" },
  { company: "Milton De Abreu's Account", code: "miltondeabreusacvvcgrowth", note: "Plano Growth" },
  { company: "Milton De Abreu's Account", code: "miltondeabreusacvvcagency", note: "Plano Agency" },
  { company: "Mirolis Financial", code: "mirolisfinancialstarter", note: "Plano Starter" },
  { company: "Mirolis Financial", code: "mirolisfinancialgrowth", note: "Plano Growth" },
  { company: "Mirolis Financial", code: "mirolisfinancialagency", note: "Plano Agency" },
  { company: "Mission", code: "missionstarter", note: "Plano Starter" },
  { company: "Mission", code: "missiongrowth", note: "Plano Growth" },
  { company: "Mission", code: "missionagency", note: "Plano Agency" },
  { company: "Money 4 Life", code: "money4lifestarter", note: "Plano Starter" },
  { company: "Money 4 Life", code: "money4lifegrowth", note: "Plano Growth" },
  { company: "Money 4 Life", code: "money4lifeagency", note: "Plano Agency" },
  { company: "Money 4 Life USA", code: "money4lifeusastarter", note: "Plano Starter" },
  { company: "Money 4 Life USA", code: "money4lifeusagrowth", note: "Plano Growth" },
  { company: "Money 4 Life USA", code: "money4lifeusaagency", note: "Plano Agency" },
  { company: "Money Growth Financial", code: "moneygrowthfina1rastarter", note: "Plano Starter" },
  { company: "Money Growth Financial", code: "moneygrowthfinan1ragrowth", note: "Plano Growth" },
  { company: "Money Growth Financial", code: "moneygrowthfinan1raagency", note: "Plano Agency" },
  { company: "Money Masters", code: "moneymastersstarter", note: "Plano Starter" },
  { company: "Money Masters", code: "moneymastersgrowth", note: "Plano Growth" },
  { company: "Money Masters", code: "moneymastersagency", note: "Plano Agency" },
  { company: "Money Matters", code: "moneymattersstarter", note: "Plano Starter" },
  { company: "Money Matters", code: "moneymattersgrowth", note: "Plano Growth" },
  { company: "Money Matters", code: "moneymattersagency", note: "Plano Agency" },
  { company: "MoneySource Management", code: "moneysourcemanaza8starter", note: "Plano Starter" },
  { company: "MoneySource Management", code: "moneysourcemanagza8growth", note: "Plano Growth" },
  { company: "MoneySource Management", code: "moneysourcemanagza8agency", note: "Plano Agency" },
  { company: "Monica Gasparetto Consulting Services", code: "monicagasparettsn4starter", note: "Plano Starter" },
  { company: "Monica Gasparetto Consulting Services", code: "monicagasparettosn4growth", note: "Plano Growth" },
  { company: "Monica Gasparetto Consulting Services", code: "monicagasparettosn4agency", note: "Plano Agency" },
  { company: "MOURA CFO", code: "mouracfostarter", note: "Plano Starter" },
  { company: "MOURA CFO", code: "mouracfogrowth", note: "Plano Growth" },
  { company: "MOURA CFO", code: "mouracfoagency", note: "Plano Agency" },
  { company: "Mynke", code: "mynkestarter", note: "Plano Starter" },
  { company: "Mynke", code: "mynkegrowth", note: "Plano Growth" },
  { company: "Mynke", code: "mynkeagency", note: "Plano Agency" },
  { company: "Neway Pools FL", code: "newaypoolsflstarter", note: "Plano Starter" },
  { company: "Neway Pools FL", code: "newaypoolsflgrowth", note: "Plano Growth" },
  { company: "Neway Pools FL", code: "newaypoolsflagency", note: "Plano Agency" },
  { company: "Neway Pools.", code: "newaypoolsstarter", note: "Plano Starter" },
  { company: "Neway Pools.", code: "newaypoolsgrowth", note: "Plano Growth" },
  { company: "Neway Pools.", code: "newaypoolsagency", note: "Plano Agency" },
  { company: "Next Level Finances", code: "nextlevelfinancesstarter", note: "Plano Starter" },
  { company: "Next Level Finances", code: "nextlevelfinancesgrowth", note: "Plano Growth" },
  { company: "Next Level Finances", code: "nextlevelfinancesagency", note: "Plano Agency" },
  { company: "Nexus", code: "nexusstarter", note: "Plano Starter" },
  { company: "Nexus", code: "nexusgrowth", note: "Plano Growth" },
  { company: "Nexus", code: "nexusagency", note: "Plano Agency" },
  { company: "NL Aquece Numero", code: "nlaquecenumerostarter", note: "Plano Starter" },
  { company: "NL Aquece Numero", code: "nlaquecenumerogrowth", note: "Plano Growth" },
  { company: "NL Aquece Numero", code: "nlaquecenumeroagency", note: "Plano Agency" },
  { company: "NSISUCESSO", code: "nsisucessostarter", note: "Plano Starter" },
  { company: "NSISUCESSO", code: "nsisucessogrowth", note: "Plano Growth" },
  { company: "NSISUCESSO", code: "nsisucessoagency", note: "Plano Agency" },
  { company: "Nuvo Capital", code: "nuvocapitalstarter", note: "Plano Starter" },
  { company: "Nuvo Capital", code: "nuvocapitalgrowth", note: "Plano Growth" },
  { company: "Nuvo Capital", code: "nuvocapitalagency", note: "Plano Agency" },
  { company: "OkFOREVER", code: "okforeverstarter", note: "Plano Starter" },
  { company: "OkFOREVER", code: "okforevergrowth", note: "Plano Growth" },
  { company: "OkFOREVER", code: "okforeveragency", note: "Plano Agency" },
  { company: "Omnys", code: "omnysstarter", note: "Plano Starter" },
  { company: "Omnys", code: "omnysgrowth", note: "Plano Growth" },
  { company: "Omnys", code: "omnysagency", note: "Plano Agency" },
  { company: "Onofre Arruda", code: "onofrearrudastarter", note: "Plano Starter" },
  { company: "Onofre Arruda", code: "onofrearrudagrowth", note: "Plano Growth" },
  { company: "Onofre Arruda", code: "onofrearrudaagency", note: "Plano Agency" },
  { company: "Onofre Linhares", code: "onofrelinharesstarter", note: "Plano Starter" },
  { company: "Onofre Linhares", code: "onofrelinharesgrowth", note: "Plano Growth" },
  { company: "Onofre Linhares", code: "onofrelinharesagency", note: "Plano Agency" },
  { company: "Opta Finance", code: "optafinancestarter", note: "Plano Starter" },
  { company: "Opta Finance", code: "optafinancegrowth", note: "Plano Growth" },
  { company: "Opta Finance", code: "optafinanceagency", note: "Plano Agency" },
  { company: "Orlux Rental", code: "orluxrentalstarter", note: "Plano Starter" },
  { company: "Orlux Rental", code: "orluxrentalgrowth", note: "Plano Growth" },
  { company: "Orlux Rental", code: "orluxrentalagency", note: "Plano Agency" },
  { company: "P3 Financial", code: "p3financialstarter", note: "Plano Starter" },
  { company: "P3 Financial", code: "p3financialgrowth", note: "Plano Growth" },
  { company: "P3 Financial", code: "p3financialagency", note: "Plano Agency" },
  { company: "Parterns Team", code: "parternsteamstarter", note: "Plano Starter" },
  { company: "Parterns Team", code: "parternsteamgrowth", note: "Plano Growth" },
  { company: "Parterns Team", code: "parternsteamagency", note: "Plano Agency" },
  { company: "Paulo Garcia", code: "paulogarciastarter", note: "Plano Starter" },
  { company: "Paulo Garcia", code: "paulogarciagrowth", note: "Plano Growth" },
  { company: "Paulo Garcia", code: "paulogarciaagency", note: "Plano Agency" },
  { company: "Pedro Poleza's Account", code: "pedropolezasacc1z0starter", note: "Plano Starter" },
  { company: "Pedro Poleza's Account", code: "pedropolezasaccountgrowth", note: "Plano Growth" },
  { company: "Pedro Poleza's Account", code: "pedropolezasaccountagency", note: "Plano Agency" },
  { company: "Pedro Polezaa", code: "pedropolezaastarter", note: "Plano Starter" },
  { company: "Pedro Polezaa", code: "pedropolezaagrowth", note: "Plano Growth" },
  { company: "Pedro Polezaa", code: "pedropolezaaagency", note: "Plano Agency" },
  { company: "PGI 2", code: "pgi2starter", note: "Plano Starter" },
  { company: "PGI 2", code: "pgi2growth", note: "Plano Growth" },
  { company: "PGI 2", code: "pgi2agency", note: "Plano Agency" },
  { company: "PGI Financial Group", code: "pgifinancialgroupstarter", note: "Plano Starter" },
  { company: "PGI Financial Group", code: "pgifinancialgroupgrowth", note: "Plano Growth" },
  { company: "PGI Financial Group", code: "pgifinancialgroupagency", note: "Plano Agency" },
  { company: "pi Legacy", code: "pilegacystarter", note: "Plano Starter" },
  { company: "pi Legacy", code: "pilegacygrowth", note: "Plano Growth" },
  { company: "pi Legacy", code: "pilegacyagency", note: "Plano Agency" },
  { company: "Pontoni Financial Corp", code: "pontonifinancia1cvstarter", note: "Plano Starter" },
  { company: "Pontoni Financial Corp", code: "pontonifinancial1cvgrowth", note: "Plano Growth" },
  { company: "Pontoni Financial Corp", code: "pontonifinancial1cvagency", note: "Plano Agency" },
  { company: "Precious Planning", code: "preciousplanningstarter", note: "Plano Starter" },
  { company: "Precious Planning", code: "preciousplanninggrowth", note: "Plano Growth" },
  { company: "Precious Planning", code: "preciousplanningagency", note: "Plano Agency" },
  { company: "Prime Immigration Office", code: "primeimmigratiofr0starter", note: "Plano Starter" },
  { company: "Prime Immigration Office", code: "primeimmigrationfr0growth", note: "Plano Growth" },
  { company: "Prime Immigration Office", code: "primeimmigrationfr0agency", note: "Plano Agency" },
  { company: "Priscilla Lacerda", code: "priscillalacerdastarter", note: "Plano Starter" },
  { company: "Priscilla Lacerda", code: "priscillalacerdagrowth", note: "Plano Growth" },
  { company: "Priscilla Lacerda", code: "priscillalacerdaagency", note: "Plano Agency" },
  { company: "Priscilla Lacerda's Account", code: "priscillalacerd1aystarter", note: "Plano Starter" },
  { company: "Priscilla Lacerda's Account", code: "priscillalacerda1aygrowth", note: "Plano Growth" },
  { company: "Priscilla Lacerda's Account", code: "priscillalacerda1ayagency", note: "Plano Agency" },
  { company: "Prosperar USA", code: "prosperarusastarter", note: "Plano Starter" },
  { company: "Prosperar USA", code: "prosperarusagrowth", note: "Plano Growth" },
  { company: "Prosperar USA", code: "prosperarusaagency", note: "Plano Agency" },
  { company: "Prosperlife Advisors", code: "prosperlifeadvi115starter", note: "Plano Starter" },
  { company: "Prosperlife Advisors", code: "prosperlifeadvisorsgrowth", note: "Plano Growth" },
  { company: "Prosperlife Advisors", code: "prosperlifeadvisorsagency", note: "Plano Agency" },
  { company: "Quantum Evolution Corp", code: "quantumevolutio16mstarter", note: "Plano Starter" },
  { company: "Quantum Evolution Corp", code: "quantumevolution16mgrowth", note: "Plano Growth" },
  { company: "Quantum Evolution Corp", code: "quantumevolution16magency", note: "Plano Agency" },
  { company: "Rafael de Paula", code: "rafaeldepaulastarter", note: "Plano Starter" },
  { company: "Rafael de Paula", code: "rafaeldepaulagrowth", note: "Plano Growth" },
  { company: "Rafael de Paula", code: "rafaeldepaulaagency", note: "Plano Agency" },
  { company: "Renata Luque Agente Financeira", code: "renataluqueagena9xstarter", note: "Plano Starter" },
  { company: "Renata Luque Agente Financeira", code: "renataluqueagenta9xgrowth", note: "Plano Growth" },
  { company: "Renata Luque Agente Financeira", code: "renataluqueagenta9xagency", note: "Plano Agency" },
  { company: "Renato Testing Account", code: "renatotestingac3tcstarter", note: "Plano Starter" },
  { company: "Renato Testing Account", code: "renatotestingacc3tcgrowth", note: "Plano Growth" },
  { company: "Renato Testing Account", code: "renatotestingacc3tcagency", note: "Plano Agency" },
  { company: "Rico$", code: "ricostarter", note: "Plano Starter" },
  { company: "Rico$", code: "ricogrowth", note: "Plano Growth" },
  { company: "Rico$", code: "ricoagency", note: "Plano Agency" },
  { company: "Riqueza na América", code: "riquezanaamericastarter", note: "Plano Starter" },
  { company: "Riqueza na América", code: "riquezanaamericagrowth", note: "Plano Growth" },
  { company: "Riqueza na América", code: "riquezanaamericaagency", note: "Plano Agency" },
  { company: "Rj Usa Money Management", code: "rjusamoneymanagq4cstarter", note: "Plano Starter" },
  { company: "Rj Usa Money Management", code: "rjusamoneymanageq4cgrowth", note: "Plano Growth" },
  { company: "Rj Usa Money Management", code: "rjusamoneymanageq4cagency", note: "Plano Agency" },
  { company: "RM STRONG FINANCIAL", code: "rmstrongfinancialstarter", note: "Plano Starter" },
  { company: "RM STRONG FINANCIAL", code: "rmstrongfinancialgrowth", note: "Plano Growth" },
  { company: "RM STRONG FINANCIAL", code: "rmstrongfinancialagency", note: "Plano Agency" },
  { company: "Ronaldo De Oliveira", code: "ronaldodeoliveirastarter", note: "Plano Starter" },
  { company: "Ronaldo De Oliveira", code: "ronaldodeoliveiragrowth", note: "Plano Growth" },
  { company: "Ronaldo De Oliveira", code: "ronaldodeoliveiraagency", note: "Plano Agency" },
  { company: "RS ACCOUNTING AND TAX", code: "rsaccountingandtaxstarter", note: "Plano Starter" },
  { company: "RS ACCOUNTING AND TAX", code: "rsaccountingandtaxgrowth", note: "Plano Growth" },
  { company: "RS ACCOUNTING AND TAX", code: "rsaccountingandtaxagency", note: "Plano Agency" },
  { company: "Sabrina Caldas", code: "sabrinacaldasstarter", note: "Plano Starter" },
  { company: "Sabrina Caldas", code: "sabrinacaldasgrowth", note: "Plano Growth" },
  { company: "Sabrina Caldas", code: "sabrinacaldasagency", note: "Plano Agency" },
  { company: "Safe Life Financial", code: "safelifefinancialstarter", note: "Plano Starter" },
  { company: "Safe Life Financial", code: "safelifefinancialgrowth", note: "Plano Growth" },
  { company: "Safe Life Financial", code: "safelifefinancialagency", note: "Plano Agency" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "scalesnapshotle1uzstarter", note: "Plano Starter" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "scalesnapshotleg1uzgrowth", note: "Plano Growth" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "scalesnapshotleg1uzagency", note: "Plano Agency" },
  { company: "Silvia Mendes", code: "silviamendesstarter", note: "Plano Starter" },
  { company: "Silvia Mendes", code: "silviamendesgrowth", note: "Plano Growth" },
  { company: "Silvia Mendes", code: "silviamendesagency", note: "Plano Agency" },
  { company: "SJ Smart Financial LLC", code: "sjsmartfinancia1w7starter", note: "Plano Starter" },
  { company: "SJ Smart Financial LLC", code: "sjsmartfinancialllcgrowth", note: "Plano Growth" },
  { company: "SJ Smart Financial LLC", code: "sjsmartfinancialllcagency", note: "Plano Agency" },
  { company: "Soneko Colchões", code: "sonekocolchoesstarter", note: "Plano Starter" },
  { company: "Soneko Colchões", code: "sonekocolchoesgrowth", note: "Plano Growth" },
  { company: "Soneko Colchões", code: "sonekocolchoesagency", note: "Plano Agency" },
  { company: "Soraia Close", code: "soraiaclosestarter", note: "Plano Starter" },
  { company: "Soraia Close", code: "soraiaclosegrowth", note: "Plano Growth" },
  { company: "Soraia Close", code: "soraiacloseagency", note: "Plano Agency" },
  { company: "South Florida Maids Pro", code: "southfloridamai1jistarter", note: "Plano Starter" },
  { company: "South Florida Maids Pro", code: "southfloridamaid1jigrowth", note: "Plano Growth" },
  { company: "South Florida Maids Pro", code: "southfloridamaid1jiagency", note: "Plano Agency" },
  { company: "Spark Demo Teste CERTO", code: "sparkdemotestecp1vstarter", note: "Plano Starter" },
  { company: "Spark Demo Teste CERTO", code: "sparkdemotestecertogrowth", note: "Plano Growth" },
  { company: "Spark Demo Teste CERTO", code: "sparkdemotestecertoagency", note: "Plano Agency" },
  { company: "Spark Leads", code: "sparkleadsstarter", note: "Plano Starter" },
  { company: "Spark Leads", code: "sparkleadsgrowth", note: "Plano Growth" },
  { company: "Spark Leads", code: "sparkleadsagency", note: "Plano Agency" },
  { company: "Spark Leadss", code: "sparkleadssstarter", note: "Plano Starter" },
  { company: "Spark Leadss", code: "sparkleadssgrowth", note: "Plano Growth" },
  { company: "Spark Leadss", code: "sparkleadssagency", note: "Plano Agency" },
  { company: "Spark Leadss FT", code: "sparkleadssftstarter", note: "Plano Starter" },
  { company: "Spark Leadss FT", code: "sparkleadssftgrowth", note: "Plano Growth" },
  { company: "Spark Leadss FT", code: "sparkleadssftagency", note: "Plano Agency" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "sparkscalev1clejnwstarter", note: "Plano Starter" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "sparkscalev1cleajnwgrowth", note: "Plano Growth" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "sparkscalev1cleajnwagency", note: "Plano Agency" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "sparkstarterv1c1yustarter", note: "Plano Starter" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "sparkstarterv1cl1yugrowth", note: "Plano Growth" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "sparkstarterv1cl1yuagency", note: "Plano Agency" },
  { company: "SparkBot", code: "sparkbotstarter", note: "Plano Starter" },
  { company: "SparkBot", code: "sparkbotgrowth", note: "Plano Growth" },
  { company: "SparkBot", code: "sparkbotagency", note: "Plano Agency" },
  { company: "SparkGo", code: "sparkgostarter", note: "Plano Starter" },
  { company: "SparkGo", code: "sparkgogrowth", note: "Plano Growth" },
  { company: "SparkGo", code: "sparkgoagency", note: "Plano Agency" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "startersnapshot55fstarter", note: "Plano Starter" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "startersnapshotl55fgrowth", note: "Plano Growth" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "startersnapshotl55fagency", note: "Plano Agency" },
  { company: "Staziaki Financial Solutions", code: "staziakifinanci1sjstarter", note: "Plano Starter" },
  { company: "Staziaki Financial Solutions", code: "staziakifinancia1sjgrowth", note: "Plano Growth" },
  { company: "Staziaki Financial Solutions", code: "staziakifinancia1sjagency", note: "Plano Agency" },
  { company: "Summit Life Financial", code: "summitlifefinan16qstarter", note: "Plano Starter" },
  { company: "Summit Life Financial", code: "summitlifefinancialgrowth", note: "Plano Growth" },
  { company: "Summit Life Financial", code: "summitlifefinancialagency", note: "Plano Agency" },
  { company: "Tatyane Rodrigues Soprani", code: "tatyanerodrigue1oestarter", note: "Plano Starter" },
  { company: "Tatyane Rodrigues Soprani", code: "tatyanerodrigues1oegrowth", note: "Plano Growth" },
  { company: "Tatyane Rodrigues Soprani", code: "tatyanerodrigues1oeagency", note: "Plano Agency" },
  { company: "Tchovas Agency", code: "tchovasagencystarter", note: "Plano Starter" },
  { company: "Tchovas Agency", code: "tchovasagencygrowth", note: "Plano Growth" },
  { company: "Tchovas Agency", code: "tchovasagencyagency", note: "Plano Agency" },
  { company: "Team De Elite", code: "teamdeelitestarter", note: "Plano Starter" },
  { company: "Team De Elite", code: "teamdeelitegrowth", note: "Plano Growth" },
  { company: "Team De Elite", code: "teamdeeliteagency", note: "Plano Agency" },
  { company: "Teste May 16", code: "testemay16starter", note: "Plano Starter" },
  { company: "Teste May 16", code: "testemay16growth", note: "Plano Growth" },
  { company: "Teste May 16", code: "testemay16agency", note: "Plano Agency" },
  { company: "TESTE PEDRO BO", code: "testepedrobostarter", note: "Plano Starter" },
  { company: "TESTE PEDRO BO", code: "testepedrobogrowth", note: "Plano Growth" },
  { company: "TESTE PEDRO BO", code: "testepedroboagency", note: "Plano Agency" },
  { company: "The Rich Life Guide", code: "therichlifeguidestarter", note: "Plano Starter" },
  { company: "The Rich Life Guide", code: "therichlifeguidegrowth", note: "Plano Growth" },
  { company: "The Rich Life Guide", code: "therichlifeguideagency", note: "Plano Agency" },
  { company: "Thiago Rabaneda", code: "thiagorabanedastarter", note: "Plano Starter" },
  { company: "Thiago Rabaneda", code: "thiagorabanedagrowth", note: "Plano Growth" },
  { company: "Thiago Rabaneda", code: "thiagorabanedaagency", note: "Plano Agency" },
  { company: "Thiago Rechi - Agente Financeiro", code: "thiagorechiagenit9starter", note: "Plano Starter" },
  { company: "Thiago Rechi - Agente Financeiro", code: "thiagorechiagentit9growth", note: "Plano Growth" },
  { company: "Thiago Rechi - Agente Financeiro", code: "thiagorechiagentit9agency", note: "Plano Agency" },
  { company: "Time Dos Prósperos", code: "timedosprosperosstarter", note: "Plano Starter" },
  { company: "Time Dos Prósperos", code: "timedosprosperosgrowth", note: "Plano Growth" },
  { company: "Time Dos Prósperos", code: "timedosprosperosagency", note: "Plano Agency" },
  { company: "Titans Agency", code: "titansagencystarter", note: "Plano Starter" },
  { company: "Titans Agency", code: "titansagencygrowth", note: "Plano Growth" },
  { company: "Titans Agency", code: "titansagencyagency", note: "Plano Agency" },
  { company: "U&M Financial", code: "umfinancialstarter", note: "Plano Starter" },
  { company: "U&M Financial", code: "umfinancialgrowth", note: "Plano Growth" },
  { company: "U&M Financial", code: "umfinancialagency", note: "Plano Agency" },
  { company: "U&M Financial Solutions", code: "umfinancialsoluj4astarter", note: "Plano Starter" },
  { company: "U&M Financial Solutions", code: "umfinancialsolutj4agrowth", note: "Plano Growth" },
  { company: "U&M Financial Solutions", code: "umfinancialsolutj4aagency", note: "Plano Agency" },
  { company: "V&F FINANCIAL SERVICES", code: "vffinancialserv1d3starter", note: "Plano Starter" },
  { company: "V&F FINANCIAL SERVICES", code: "vffinancialservicesgrowth", note: "Plano Growth" },
  { company: "V&F FINANCIAL SERVICES", code: "vffinancialservicesagency", note: "Plano Agency" },
  { company: "ValeriaSartori", code: "valeriasartoristarter", note: "Plano Starter" },
  { company: "ValeriaSartori", code: "valeriasartorigrowth", note: "Plano Growth" },
  { company: "ValeriaSartori", code: "valeriasartoriagency", note: "Plano Agency" },
  { company: "Vasti Rodrigues", code: "vastirodriguesstarter", note: "Plano Starter" },
  { company: "Vasti Rodrigues", code: "vastirodriguesgrowth", note: "Plano Growth" },
  { company: "Vasti Rodrigues", code: "vastirodriguesagency", note: "Plano Agency" },
  { company: "Victor Costa", code: "victorcostastarter", note: "Plano Starter" },
  { company: "Victor Costa", code: "victorcostagrowth", note: "Plano Growth" },
  { company: "Victor Costa", code: "victorcostaagency", note: "Plano Agency" },
  { company: "Vida Bela", code: "vidabelastarter", note: "Plano Starter" },
  { company: "Vida Bela", code: "vidabelagrowth", note: "Plano Growth" },
  { company: "Vida Bela", code: "vidabelaagency", note: "Plano Agency" },
  { company: "Vida Bela LLC", code: "vidabelallcstarter", note: "Plano Starter" },
  { company: "Vida Bela LLC", code: "vidabelallcgrowth", note: "Plano Growth" },
  { company: "Vida Bela LLC", code: "vidabelallcagency", note: "Plano Agency" },
  { company: "Vincit Capital", code: "vincitcapitalstarter", note: "Plano Starter" },
  { company: "Vincit Capital", code: "vincitcapitalgrowth", note: "Plano Growth" },
  { company: "Vincit Capital", code: "vincitcapitalagency", note: "Plano Agency" },
  { company: "Vinicius Mora's Account", code: "viniciusmorasac5oastarter", note: "Plano Starter" },
  { company: "Vinicius Mora's Account", code: "viniciusmorasacc5oagrowth", note: "Plano Growth" },
  { company: "Vinicius Mora's Account", code: "viniciusmorasacc5oaagency", note: "Plano Agency" },
  { company: "Vinicius Moraes", code: "viniciusmoraesstarter", note: "Plano Starter" },
  { company: "Vinicius Moraes", code: "viniciusmoraesgrowth", note: "Plano Growth" },
  { company: "Vinicius Moraes", code: "viniciusmoraesagency", note: "Plano Agency" },
  { company: "Vision Group", code: "visiongroupstarter", note: "Plano Starter" },
  { company: "Vision Group", code: "visiongroupgrowth", note: "Plano Growth" },
  { company: "Vision Group", code: "visiongroupagency", note: "Plano Agency" },
  { company: "Vivian Osorio's Account", code: "vivianosoriosacsb9starter", note: "Plano Starter" },
  { company: "Vivian Osorio's Account", code: "vivianosoriosaccsb9growth", note: "Plano Growth" },
  { company: "Vivian Osorio's Account", code: "vivianosoriosaccsb9agency", note: "Plano Agency" },
  { company: "Viviane Goellner", code: "vivianegoellnerstarter", note: "Plano Starter" },
  { company: "Viviane Goellner", code: "vivianegoellnergrowth", note: "Plano Growth" },
  { company: "Viviane Goellner", code: "vivianegoellneragency", note: "Plano Agency" },
  { company: "Viviane Quinalha", code: "vivianequinalhastarter", note: "Plano Starter" },
  { company: "Viviane Quinalha", code: "vivianequinalhagrowth", note: "Plano Growth" },
  { company: "Viviane Quinalha", code: "vivianequinalhaagency", note: "Plano Agency" },
  { company: "Viviane Rodrigues's Account", code: "vivianerodrigueuo0starter", note: "Plano Starter" },
  { company: "Viviane Rodrigues's Account", code: "vivianerodriguesuo0growth", note: "Plano Growth" },
  { company: "Viviane Rodrigues's Account", code: "vivianerodriguesuo0agency", note: "Plano Agency" },
  { company: "Wagner Witka's Account", code: "wagnerwitkasaccf8cstarter", note: "Plano Starter" },
  { company: "Wagner Witka's Account", code: "wagnerwitkasaccountgrowth", note: "Plano Growth" },
  { company: "Wagner Witka's Account", code: "wagnerwitkasaccountagency", note: "Plano Agency" },
  { company: "WattsUpEnergy", code: "wattsupenergystarter", note: "Plano Starter" },
  { company: "WattsUpEnergy", code: "wattsupenergygrowth", note: "Plano Growth" },
  { company: "WattsUpEnergy", code: "wattsupenergyagency", note: "Plano Agency" },
  { company: "Wise Wallet Financial", code: "wisewalletfinan649starter", note: "Plano Starter" },
  { company: "Wise Wallet Financial", code: "wisewalletfinancialgrowth", note: "Plano Growth" },
  { company: "Wise Wallet Financial", code: "wisewalletfinancialagency", note: "Plano Agency" },
  { company: "Witka Financial", code: "witkafinancialstarter", note: "Plano Starter" },
  { company: "Witka Financial", code: "witkafinancialgrowth", note: "Plano Growth" },
  { company: "Witka Financial", code: "witkafinancialagency", note: "Plano Agency" },
  { company: "ZAP Guilherme", code: "zapguilhermestarter", note: "Plano Starter" },
  { company: "ZAP Guilherme", code: "zapguilhermegrowth", note: "Plano Growth" },
  { company: "ZAP Guilherme", code: "zapguilhermeagency", note: "Plano Agency" },
  { company: "ZAPIER Testing Account", code: "zapiertestingacmjrstarter", note: "Plano Starter" },
  { company: "ZAPIER Testing Account", code: "zapiertestingaccmjrgrowth", note: "Plano Growth" },
  { company: "ZAPIER Testing Account", code: "zapiertestingaccmjragency", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "orfapodedeletardghstarter", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "orfapodedeletarsdghgrowth", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "orfapodedeletarsdghagency", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "orfapodedeletar132starter", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "orfapodedeletars132growth", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "orfapodedeletars132agency", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "orfapodedeletar1ghstarter", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "orfapodedeletars1ghgrowth", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "orfapodedeletars1ghagency", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "orfapodedeletarn2estarter", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "orfapodedeletartestgrowth", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "orfapodedeletartestagency", note: "Plano Agency" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "sparkgrowthv1maogqstarter", note: "Plano Starter" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "sparkgrowthv1mastergrowth", note: "Plano Growth" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "sparkgrowthv1masteragency", note: "Plano Agency" },
];
