// GERADO a partir dos cupons reais do GHL — não editar à mão.
// Códigos exatos (MAIÚSCULOS) como o GHL armazena, para casar no checkout.
import type { Coupon } from "./coupons";

export const GHL_COUPONS: Coupon[] = [
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "ORFAPODEDELETARSDGHAGENCY", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "ORFAPODEDELETARSDGHGROWTH", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Agency Master v1)", code: "ORFAPODEDELETARDGHSTARTER", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "ORFAPODEDELETARS132AGENCY", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "ORFAPODEDELETARS132GROWTH", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1 dup)", code: "ORFAPODEDELETAR132STARTER", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "ORFAPODEDELETARS1GHAGENCY", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "ORFAPODEDELETARS1GHGROWTH", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (Spark Starter Master v1)", code: "ORFAPODEDELETAR1GHSTARTER", note: "Plano Starter" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "ORFAPODEDELETARTESTAGENCY", note: "Plano Agency" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "ORFAPODEDELETARTESTGROWTH", note: "Plano Growth" },
  { company: "⚠️ ORFA — pode deletar (TEST)", code: "ORFAPODEDELETARN2ESTARTER", note: "Plano Starter" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "SPARKGROWTHV1MASTERAGENCY", note: "Plano Agency" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "SPARKGROWTHV1MASTERGROWTH", note: "Plano Growth" },
  { company: "🚀 Spark Growth v1 — MASTER", code: "SPARKGROWTHV1MAOGQSTARTER", note: "Plano Starter" },
  { company: "3 T Financial Solution", code: "3TFINANCIALSOLUTIONAGENCY", note: "Plano Agency" },
  { company: "3 T Financial Solution", code: "3TFINANCIALSOLUTIONGROWTH", note: "Plano Growth" },
  { company: "3 T Financial Solution", code: "3TFINANCIALSOLUQUFSTARTER", note: "Plano Starter" },
  { company: "3t", code: "3TAGENCY", note: "Plano Agency" },
  { company: "3t", code: "3TGROWTH", note: "Plano Growth" },
  { company: "3t", code: "3TSTARTER", note: "Plano Starter" },
  { company: "3T Financial General Account", code: "3TFINANCIALGENER7NQAGENCY", note: "Plano Agency" },
  { company: "3T Financial General Account", code: "3TFINANCIALGENER7NQGROWTH", note: "Plano Growth" },
  { company: "3T Financial General Account", code: "3TFINANCIALGENE7NQSTARTER", note: "Plano Starter" },
  { company: "3t Financial Group", code: "3TFINANCIALGROUPAGENCY", note: "Plano Agency" },
  { company: "3t Financial Group", code: "3TFINANCIALGROUPGROWTH", note: "Plano Growth" },
  { company: "3t Financial Group", code: "3TFINANCIALGROUPSTARTER", note: "Plano Starter" },
  { company: "5 Rings", code: "5RINGSAGENCY", note: "Plano Agency" },
  { company: "5 Rings", code: "5RINGSGROWTH", note: "Plano Growth" },
  { company: "5 Rings", code: "5RINGSSTARTER", note: "Plano Starter" },
  { company: "A Forja Financial", code: "AFORJAFINANCIALAGENCY", note: "Plano Agency" },
  { company: "A Forja Financial", code: "AFORJAFINANCIALGROWTH", note: "Plano Growth" },
  { company: "A Forja Financial", code: "AFORJAFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Absoluto", code: "ABSOLUTOAGENCY", note: "Plano Agency" },
  { company: "Absoluto", code: "ABSOLUTOGROWTH", note: "Plano Growth" },
  { company: "Absoluto", code: "ABSOLUTOSTARTER", note: "Plano Starter" },
  { company: "Ademo Financial Group", code: "ADEMOFINANCIALGROUPAGENCY", note: "Plano Agency" },
  { company: "Ademo Financial Group", code: "ADEMOFINANCIALGROUPGROWTH", note: "Plano Growth" },
  { company: "Ademo Financial Group", code: "ADEMOFINANCIALG1GNSTARTER", note: "Plano Starter" },
  { company: "Adriano Buzolin Cruz", code: "ADRIANOBUZOLINCRUZAGENCY", note: "Plano Agency" },
  { company: "Adriano Buzolin Cruz", code: "ADRIANOBUZOLINCRUZGROWTH", note: "Plano Growth" },
  { company: "Adriano Buzolin Cruz", code: "ADRIANOBUZOLINCRUZSTARTER", note: "Plano Starter" },
  { company: "Agency Over Wan", code: "AGENCYOVERWANAGENCY", note: "Plano Agency" },
  { company: "Agency Over Wan", code: "AGENCYOVERWANGROWTH", note: "Plano Growth" },
  { company: "Agency Over Wan", code: "AGENCYOVERWANSTARTER", note: "Plano Starter" },
  { company: "Agency Snapshot Clean Master v1", code: "AGENCYSNAPSHOTCLRCJAGENCY", note: "Plano Agency" },
  { company: "Agency Snapshot Clean Master v1", code: "AGENCYSNAPSHOTCLRCJGROWTH", note: "Plano Growth" },
  { company: "Agency Snapshot Clean Master v1", code: "AGENCYSNAPSHOTCRCJSTARTER", note: "Plano Starter" },
  { company: "Agente Financeiro", code: "AGENTEFINANCEIROAGENCY", note: "Plano Agency" },
  { company: "Agente Financeiro", code: "AGENTEFINANCEIROGROWTH", note: "Plano Growth" },
  { company: "Agente Financeiro", code: "AGENTEFINANCEIROSTARTER", note: "Plano Starter" },
  { company: "AI Chat Creation", code: "AICHATCREATIONAGENCY", note: "Plano Agency" },
  { company: "AI Chat Creation", code: "AICHATCREATIONGROWTH", note: "Plano Growth" },
  { company: "AI Chat Creation", code: "AICHATCREATIONSTARTER", note: "Plano Starter" },
  { company: "Airam Da Silva", code: "AIRAMDASILVAAGENCY", note: "Plano Agency" },
  { company: "Airam Da Silva", code: "AIRAMDASILVAGROWTH", note: "Plano Growth" },
  { company: "Airam Da Silva", code: "AIRAMDASILVASTARTER", note: "Plano Starter" },
  { company: "Alaska Tech Store", code: "ALASKATECHSTOREAGENCY", note: "Plano Agency" },
  { company: "Alaska Tech Store", code: "ALASKATECHSTOREGROWTH", note: "Plano Growth" },
  { company: "Alaska Tech Store", code: "ALASKATECHSTORESTARTER", note: "Plano Starter" },
  { company: "Aleteia", code: "ALETEIAAGENCY", note: "Plano Agency" },
  { company: "Aleteia", code: "ALETEIAGROWTH", note: "Plano Growth" },
  { company: "Aleteia", code: "ALETEIASTARTER", note: "Plano Starter" },
  { company: "Alive", code: "ALIVEAGENCY", note: "Plano Agency" },
  { company: "Alive", code: "ALIVEGROWTH", note: "Plano Growth" },
  { company: "Alive", code: "ALIVESTARTER", note: "Plano Starter" },
  { company: "All In Financial", code: "ALLINFINANCIALAGENCY", note: "Plano Agency" },
  { company: "All In Financial", code: "ALLINFINANCIALGROWTH", note: "Plano Growth" },
  { company: "All In Financial", code: "ALLINFINANCIALSTARTER", note: "Plano Starter" },
  { company: "AllBridge Solutions", code: "ALLBRIDGESOLUTIONSAGENCY", note: "Plano Agency" },
  { company: "AllBridge Solutions", code: "ALLBRIDGESOLUTIONSGROWTH", note: "Plano Growth" },
  { company: "AllBridge Solutions", code: "ALLBRIDGESOLUTIONSSTARTER", note: "Plano Starter" },
  { company: "Allure Capital", code: "ALLURECAPITALAGENCY", note: "Plano Agency" },
  { company: "Allure Capital", code: "ALLURECAPITALGROWTH", note: "Plano Growth" },
  { company: "Allure Capital", code: "ALLURECAPITALSTARTER", note: "Plano Starter" },
  { company: "Alves Cury Clients", code: "ALVESCURYCLIENTSAGENCY", note: "Plano Agency" },
  { company: "Alves Cury Clients", code: "ALVESCURYCLIENTSGROWTH", note: "Plano Growth" },
  { company: "Alves Cury Clients", code: "ALVESCURYCLIENTSSTARTER", note: "Plano Starter" },
  { company: "Alves Cury Financial", code: "ALVESCURYFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Alves Cury Financial", code: "ALVESCURYFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Alves Cury Financial", code: "ALVESCURYFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Ana Carvalho", code: "ANACARVALHOAGENCY", note: "Plano Agency" },
  { company: "Ana Carvalho", code: "ANACARVALHOGROWTH", note: "Plano Growth" },
  { company: "Ana Carvalho", code: "ANACARVALHOSTARTER", note: "Plano Starter" },
  { company: "Ana Paula Lemika", code: "ANAPAULALEMIKAAGENCY", note: "Plano Agency" },
  { company: "Ana Paula Lemika", code: "ANAPAULALEMIKAGROWTH", note: "Plano Growth" },
  { company: "Ana Paula Lemika", code: "ANAPAULALEMIKASTARTER", note: "Plano Starter" },
  { company: "Ana Paula Rangel", code: "ANAPAULARANGELAGENCY", note: "Plano Agency" },
  { company: "Ana Paula Rangel", code: "ANAPAULARANGELGROWTH", note: "Plano Growth" },
  { company: "Ana Paula Rangel", code: "ANAPAULARANGELSTARTER", note: "Plano Starter" },
  { company: "Ana Sendir", code: "ANASENDIRAGENCY", note: "Plano Agency" },
  { company: "Ana Sendir", code: "ANASENDIRGROWTH", note: "Plano Growth" },
  { company: "Ana Sendir", code: "ANASENDIRSTARTER", note: "Plano Starter" },
  { company: "Anderson Mendes de Carvalho's Account", code: "ANDERSONMENDESDE1IXAGENCY", note: "Plano Agency" },
  { company: "Anderson Mendes de Carvalho's Account", code: "ANDERSONMENDESDE1IXGROWTH", note: "Plano Growth" },
  { company: "Anderson Mendes de Carvalho's Account", code: "ANDERSONMENDESD1IXSTARTER", note: "Plano Starter" },
  { company: "Andréia Carreiro", code: "ANDREIACARREIROAGENCY", note: "Plano Agency" },
  { company: "Andréia Carreiro", code: "ANDREIACARREIROGROWTH", note: "Plano Growth" },
  { company: "Andréia Carreiro", code: "ANDREIACARREIROSTARTER", note: "Plano Starter" },
  { company: "Andreza Cordutsky", code: "ANDREZACORDUTSKYAGENCY", note: "Plano Agency" },
  { company: "Andreza Cordutsky", code: "ANDREZACORDUTSKYGROWTH", note: "Plano Growth" },
  { company: "Andreza Cordutsky", code: "ANDREZACORDUTSKYSTARTER", note: "Plano Starter" },
  { company: "ANTONIO RAMPAZZO", code: "ANTONIORAMPAZZOAGENCY", note: "Plano Agency" },
  { company: "ANTONIO RAMPAZZO", code: "ANTONIORAMPAZZOGROWTH", note: "Plano Growth" },
  { company: "ANTONIO RAMPAZZO", code: "ANTONIORAMPAZZOSTARTER", note: "Plano Starter" },
  { company: "Ariane", code: "ARIANEAGENCY", note: "Plano Agency" },
  { company: "Ariane", code: "ARIANEGROWTH", note: "Plano Growth" },
  { company: "Ariane", code: "ARIANESTARTER", note: "Plano Starter" },
  { company: "Ark Financial", code: "ARKFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Ark Financial", code: "ARKFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Ark Financial", code: "ARKFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Ashyley Cardoso", code: "ASHYLEYCARDOSOAGENCY", note: "Plano Agency" },
  { company: "Ashyley Cardoso", code: "ASHYLEYCARDOSOGROWTH", note: "Plano Growth" },
  { company: "Ashyley Cardoso", code: "ASHYLEYCARDOSOSTARTER", note: "Plano Starter" },
  { company: "Bautz Life Insurance", code: "BAUTZLIFEINSURANCEAGENCY", note: "Plano Agency" },
  { company: "Bautz Life Insurance", code: "BAUTZLIFEINSURANCEGROWTH", note: "Plano Growth" },
  { company: "Bautz Life Insurance", code: "BAUTZLIFEINSURANCESTARTER", note: "Plano Starter" },
  { company: "Bella Luna Llc", code: "BELLALUNALLCAGENCY", note: "Plano Agency" },
  { company: "Bella Luna Llc", code: "BELLALUNALLCGROWTH", note: "Plano Growth" },
  { company: "Bella Luna Llc", code: "BELLALUNALLCSTARTER", note: "Plano Starter" },
  { company: "Better Life Financial", code: "BETTERLIFEFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Better Life Financial", code: "BETTERLIFEFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Better Life Financial", code: "BETTERLIFEFINANM5ZSTARTER", note: "Plano Starter" },
  { company: "Bia Prado", code: "BIAPRADOAGENCY", note: "Plano Agency" },
  { company: "Bia Prado", code: "BIAPRADOGROWTH", note: "Plano Growth" },
  { company: "Bia Prado", code: "BIAPRADOSTARTER", note: "Plano Starter" },
  { company: "Bianca Broglio", code: "BIANCABROGLIOAGENCY", note: "Plano Agency" },
  { company: "Bianca Broglio", code: "BIANCABROGLIOGROWTH", note: "Plano Growth" },
  { company: "Bianca Broglio", code: "BIANCABROGLIOSTARTER", note: "Plano Starter" },
  { company: "Bigagency Finance Specialists", code: "BIGAGENCYFINANCE71IAGENCY", note: "Plano Agency" },
  { company: "Bigagency Finance Specialists", code: "BIGAGENCYFINANCE71IGROWTH", note: "Plano Growth" },
  { company: "Bigagency Finance Specialists", code: "BIGAGENCYFINANC71ISTARTER", note: "Plano Starter" },
  { company: "Black F", code: "BLACKFAGENCY", note: "Plano Agency" },
  { company: "Black F", code: "BLACKFGROWTH", note: "Plano Growth" },
  { company: "Black F", code: "BLACKFSTARTER", note: "Plano Starter" },
  { company: "Black Financial Freedom", code: "BLACKFINANCIALFRBYNAGENCY", note: "Plano Agency" },
  { company: "Black Financial Freedom", code: "BLACKFINANCIALFRBYNGROWTH", note: "Plano Growth" },
  { company: "Black Financial Freedom", code: "BLACKFINANCIALFBYNSTARTER", note: "Plano Starter" },
  { company: "Br Usa Business", code: "BRUSABUSINESSAGENCY", note: "Plano Agency" },
  { company: "Br Usa Business", code: "BRUSABUSINESSGROWTH", note: "Plano Growth" },
  { company: "Br Usa Business", code: "BRUSABUSINESSSTARTER", note: "Plano Starter" },
  { company: "Braga-Lett Financial", code: "BRAGALETTFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Braga-Lett Financial", code: "BRAGALETTFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Braga-Lett Financial", code: "BRAGALETTFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Buba Rufino", code: "BUBARUFINOAGENCY", note: "Plano Agency" },
  { company: "Buba Rufino", code: "BUBARUFINOGROWTH", note: "Plano Growth" },
  { company: "Buba Rufino", code: "BUBARUFINOSTARTER", note: "Plano Starter" },
  { company: "by Mertz", code: "BYMERTZAGENCY", note: "Plano Agency" },
  { company: "by Mertz", code: "BYMERTZGROWTH", note: "Plano Growth" },
  { company: "by Mertz", code: "BYMERTZSTARTER", note: "Plano Starter" },
  { company: "Carla Konno", code: "CARLAKONNOAGENCY", note: "Plano Agency" },
  { company: "Carla Konno", code: "CARLAKONNOGROWTH", note: "Plano Growth" },
  { company: "Carla Konno", code: "CARLAKONNOSTARTER", note: "Plano Starter" },
  { company: "Carolina Cabellos", code: "CAROLINACABELLOSAGENCY", note: "Plano Agency" },
  { company: "Carolina Cabellos", code: "CAROLINACABELLOSGROWTH", note: "Plano Growth" },
  { company: "Carolina Cabellos", code: "CAROLINACABELLOSSTARTER", note: "Plano Starter" },
  { company: "Caroline Alexandre Da Silva's Account", code: "CAROLINEALEXANDRKG3AGENCY", note: "Plano Agency" },
  { company: "Caroline Alexandre Da Silva's Account", code: "CAROLINEALEXANDRKG3GROWTH", note: "Plano Growth" },
  { company: "Caroline Alexandre Da Silva's Account", code: "CAROLINEALEXANDKG3STARTER", note: "Plano Starter" },
  { company: "Casa Do Poder", code: "CASADOPODERAGENCY", note: "Plano Agency" },
  { company: "Casa Do Poder", code: "CASADOPODERGROWTH", note: "Plano Growth" },
  { company: "Casa Do Poder", code: "CASADOPODERSTARTER", note: "Plano Starter" },
  { company: "Cbc Financial Solutions", code: "CBCFINANCIALSOLUJQWAGENCY", note: "Plano Agency" },
  { company: "Cbc Financial Solutions", code: "CBCFINANCIALSOLUJQWGROWTH", note: "Plano Growth" },
  { company: "Cbc Financial Solutions", code: "CBCFINANCIALSOLJQWSTARTER", note: "Plano Starter" },
  { company: "Charles Dantas's Account", code: "CHARLESDANTASSAC14TAGENCY", note: "Plano Agency" },
  { company: "Charles Dantas's Account", code: "CHARLESDANTASSAC14TGROWTH", note: "Plano Growth" },
  { company: "Charles Dantas's Account", code: "CHARLESDANTASSA14TSTARTER", note: "Plano Starter" },
  { company: "Claudia Fehribach", code: "CLAUDIAFEHRIBACHAGENCY", note: "Plano Agency" },
  { company: "Claudia Fehribach", code: "CLAUDIAFEHRIBACHGROWTH", note: "Plano Growth" },
  { company: "Claudia Fehribach", code: "CLAUDIAFEHRIBACHSTARTER", note: "Plano Starter" },
  { company: "Claudio Santos's Account", code: "CLAUDIOSANTOSSACL5VAGENCY", note: "Plano Agency" },
  { company: "Claudio Santos's Account", code: "CLAUDIOSANTOSSACL5VGROWTH", note: "Plano Growth" },
  { company: "Claudio Santos's Account", code: "CLAUDIOSANTOSSAL5VSTARTER", note: "Plano Starter" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "CMFINANCIALSOLUTJZXAGENCY", note: "Plano Agency" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "CMFINANCIALSOLUTJZXGROWTH", note: "Plano Growth" },
  { company: "Cm Financial Solutions Inc/ Ricos", code: "CMFINANCIALSOLUJZXSTARTER", note: "Plano Starter" },
  { company: "Coiro Finances", code: "COIROFINANCESAGENCY", note: "Plano Agency" },
  { company: "Coiro Finances", code: "COIROFINANCESGROWTH", note: "Plano Growth" },
  { company: "Coiro Finances", code: "COIROFINANCESSTARTER", note: "Plano Starter" },
  { company: "Construction Connection", code: "CONSTRUCTIONCONN106AGENCY", note: "Plano Agency" },
  { company: "Construction Connection", code: "CONSTRUCTIONCONN106GROWTH", note: "Plano Growth" },
  { company: "Construction Connection", code: "CONSTRUCTIONCON106STARTER", note: "Plano Starter" },
  { company: "CROSS Alliance Agency", code: "CROSSALLIANCEAGENCYAGENCY", note: "Plano Agency" },
  { company: "CROSS Alliance Agency", code: "CROSSALLIANCEAGENCYGROWTH", note: "Plano Growth" },
  { company: "CROSS Alliance Agency", code: "CROSSALLIANCEAG19GSTARTER", note: "Plano Starter" },
  { company: "Cynthia Avelar", code: "CYNTHIAAVELARAGENCY", note: "Plano Agency" },
  { company: "Cynthia Avelar", code: "CYNTHIAAVELARGROWTH", note: "Plano Growth" },
  { company: "Cynthia Avelar", code: "CYNTHIAAVELARSTARTER", note: "Plano Starter" },
  { company: "Cynthia Avelar's Account", code: "CYNTHIAAVELARSAC1P6AGENCY", note: "Plano Agency" },
  { company: "Cynthia Avelar's Account", code: "CYNTHIAAVELARSAC1P6GROWTH", note: "Plano Growth" },
  { company: "Cynthia Avelar's Account", code: "CYNTHIAAVELARSA1P6STARTER", note: "Plano Starter" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "DGONCALVESMONTEIWWGAGENCY", note: "Plano Agency" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "DGONCALVESMONTEIWWGGROWTH", note: "Plano Growth" },
  { company: "D GONCALVES MONTEIRO DA SI's Account", code: "DGONCALVESMONTEWWGSTARTER", note: "Plano Starter" },
  { company: "D&M Financial", code: "DMFINANCIALAGENCY", note: "Plano Agency" },
  { company: "D&M Financial", code: "DMFINANCIALGROWTH", note: "Plano Growth" },
  { company: "D&M Financial", code: "DMFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Daniely Jones", code: "DANIELYJONESAGENCY", note: "Plano Agency" },
  { company: "Daniely Jones", code: "DANIELYJONESGROWTH", note: "Plano Growth" },
  { company: "Daniely Jones", code: "DANIELYJONESSTARTER", note: "Plano Starter" },
  { company: "Dannyele", code: "DANNYELEAGENCY", note: "Plano Agency" },
  { company: "Dannyele", code: "DANNYELEGROWTH", note: "Plano Growth" },
  { company: "Dannyele", code: "DANNYELESTARTER", note: "Plano Starter" },
  { company: "Dina Souza", code: "DINASOUZAAGENCY", note: "Plano Agency" },
  { company: "Dina Souza", code: "DINASOUZAGROWTH", note: "Plano Growth" },
  { company: "Dina Souza", code: "DINASOUZASTARTER", note: "Plano Starter" },
  { company: "Djessica Bocardi", code: "DJESSICABOCARDIAGENCY", note: "Plano Agency" },
  { company: "Djessica Bocardi", code: "DJESSICABOCARDIGROWTH", note: "Plano Growth" },
  { company: "Djessica Bocardi", code: "DJESSICABOCARDISTARTER", note: "Plano Starter" },
  { company: "Douglas E Thaiana", code: "DOUGLASETHAIANAAGENCY", note: "Plano Agency" },
  { company: "Douglas E Thaiana", code: "DOUGLASETHAIANAGROWTH", note: "Plano Growth" },
  { company: "Douglas E Thaiana", code: "DOUGLASETHAIANASTARTER", note: "Plano Starter" },
  { company: "Dream Makers Financial", code: "DREAMMAKERSFINAN1RBAGENCY", note: "Plano Agency" },
  { company: "Dream Makers Financial", code: "DREAMMAKERSFINAN1RBGROWTH", note: "Plano Growth" },
  { company: "Dream Makers Financial", code: "DREAMMAKERSFINA1RBSTARTER", note: "Plano Starter" },
  { company: "Dream Team - Fernando & Ellyn", code: "DREAMTEAMFERNANDSLQAGENCY", note: "Plano Agency" },
  { company: "Dream Team - Fernando & Ellyn", code: "DREAMTEAMFERNANDSLQGROWTH", note: "Plano Growth" },
  { company: "Dream Team - Fernando & Ellyn", code: "DREAMTEAMFERNANSLQSTARTER", note: "Plano Starter" },
  { company: "Dreamers Financial", code: "DREAMERSFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Dreamers Financial", code: "DREAMERSFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Dreamers Financial", code: "DREAMERSFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Drive ON Autos", code: "DRIVEONAUTOSAGENCY", note: "Plano Agency" },
  { company: "Drive ON Autos", code: "DRIVEONAUTOSGROWTH", note: "Plano Growth" },
  { company: "Drive ON Autos", code: "DRIVEONAUTOSSTARTER", note: "Plano Starter" },
  { company: "Drive ON Subscriptions", code: "DRIVEONSUBSCRIPTO8AAGENCY", note: "Plano Agency" },
  { company: "Drive ON Subscriptions", code: "DRIVEONSUBSCRIPTO8AGROWTH", note: "Plano Growth" },
  { company: "Drive ON Subscriptions", code: "DRIVEONSUBSCRIPO8ASTARTER", note: "Plano Starter" },
  { company: "DTLBiz", code: "DTLBIZAGENCY", note: "Plano Agency" },
  { company: "DTLBiz", code: "DTLBIZGROWTH", note: "Plano Growth" },
  { company: "DTLBiz", code: "DTLBIZSTARTER", note: "Plano Starter" },
  { company: "e-Z Accounting Services Inc", code: "EZACCOUNTINGSERVOG5AGENCY", note: "Plano Agency" },
  { company: "e-Z Accounting Services Inc", code: "EZACCOUNTINGSERVOG5GROWTH", note: "Plano Growth" },
  { company: "e-Z Accounting Services Inc", code: "EZACCOUNTINGSEROG5STARTER", note: "Plano Starter" },
  { company: "Elevated Wealth", code: "ELEVATEDWEALTHAGENCY", note: "Plano Agency" },
  { company: "Elevated Wealth", code: "ELEVATEDWEALTHGROWTH", note: "Plano Growth" },
  { company: "Elevated Wealth", code: "ELEVATEDWEALTHSTARTER", note: "Plano Starter" },
  { company: "Eliane de Souza", code: "ELIANEDESOUZAAGENCY", note: "Plano Agency" },
  { company: "Eliane de Souza", code: "ELIANEDESOUZAGROWTH", note: "Plano Growth" },
  { company: "Eliane de Souza", code: "ELIANEDESOUZASTARTER", note: "Plano Starter" },
  { company: "Eliane Melo", code: "ELIANEMELOAGENCY", note: "Plano Agency" },
  { company: "Eliane Melo", code: "ELIANEMELOGROWTH", note: "Plano Growth" },
  { company: "Eliane Melo", code: "ELIANEMELOSTARTER", note: "Plano Starter" },
  { company: "ELITE FINANCIAL", code: "ELITEFINANCIALAGENCY", note: "Plano Agency" },
  { company: "ELITE FINANCIAL", code: "ELITEFINANCIALGROWTH", note: "Plano Growth" },
  { company: "ELITE FINANCIAL", code: "ELITEFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Espaço Se Conecte", code: "ESPACOSECONECTEAGENCY", note: "Plano Agency" },
  { company: "Espaço Se Conecte", code: "ESPACOSECONECTEGROWTH", note: "Plano Growth" },
  { company: "Espaço Se Conecte", code: "ESPACOSECONECTESTARTER", note: "Plano Starter" },
  { company: "EverRise Co.", code: "EVERRISECOAGENCY", note: "Plano Agency" },
  { company: "EverRise Co.", code: "EVERRISECOGROWTH", note: "Plano Growth" },
  { company: "EverRise Co.", code: "EVERRISECOSTARTER", note: "Plano Starter" },
  { company: "EverSafe Life Solutions", code: "EVERSAFELIFESOLU1SMAGENCY", note: "Plano Agency" },
  { company: "EverSafe Life Solutions", code: "EVERSAFELIFESOLU1SMGROWTH", note: "Plano Growth" },
  { company: "EverSafe Life Solutions", code: "EVERSAFELIFESOL1SMSTARTER", note: "Plano Starter" },
  { company: "Face Beauty", code: "FACEBEAUTYAGENCY", note: "Plano Agency" },
  { company: "Face Beauty", code: "FACEBEAUTYGROWTH", note: "Plano Growth" },
  { company: "Face Beauty", code: "FACEBEAUTYSTARTER", note: "Plano Starter" },
  { company: "Fad Financial Solutions", code: "FADFINANCIALSOLU8LVAGENCY", note: "Plano Agency" },
  { company: "Fad Financial Solutions", code: "FADFINANCIALSOLU8LVGROWTH", note: "Plano Growth" },
  { company: "Fad Financial Solutions", code: "FADFINANCIALSOL8LVSTARTER", note: "Plano Starter" },
  { company: "Fernanda Pontoni", code: "FERNANDAPONTONIAGENCY", note: "Plano Agency" },
  { company: "Fernanda Pontoni", code: "FERNANDAPONTONIGROWTH", note: "Plano Growth" },
  { company: "Fernanda Pontoni", code: "FERNANDAPONTONISTARTER", note: "Plano Starter" },
  { company: "Financial Peace Usa", code: "FINANCIALPEACEUSAAGENCY", note: "Plano Agency" },
  { company: "Financial Peace Usa", code: "FINANCIALPEACEUSAGROWTH", note: "Plano Growth" },
  { company: "Financial Peace Usa", code: "FINANCIALPEACEUSASTARTER", note: "Plano Starter" },
  { company: "Financial Star", code: "FINANCIALSTARAGENCY", note: "Plano Agency" },
  { company: "Financial Star", code: "FINANCIALSTARGROWTH", note: "Plano Growth" },
  { company: "Financial Star", code: "FINANCIALSTARSTARTER", note: "Plano Starter" },
  { company: "Finexpress Mortgage", code: "FINEXPRESSMORTGAGEAGENCY", note: "Plano Agency" },
  { company: "Finexpress Mortgage", code: "FINEXPRESSMORTGAGEGROWTH", note: "Plano Growth" },
  { company: "Finexpress Mortgage", code: "FINEXPRESSMORTGAGESTARTER", note: "Plano Starter" },
  { company: "Fire Financial", code: "FIREFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Fire Financial", code: "FIREFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Fire Financial", code: "FIREFINANCIALSTARTER", note: "Plano Starter" },
  { company: "First Class Financial", code: "FIRSTCLASSFINANCIALAGENCY", note: "Plano Agency" },
  { company: "First Class Financial", code: "FIRSTCLASSFINANCIALGROWTH", note: "Plano Growth" },
  { company: "First Class Financial", code: "FIRSTCLASSFINANBBXSTARTER", note: "Plano Starter" },
  { company: "Five Rings", code: "FIVERINGSAGENCY", note: "Plano Agency" },
  { company: "Five Rings", code: "FIVERINGSGROWTH", note: "Plano Growth" },
  { company: "Five Rings", code: "FIVERINGSSTARTER", note: "Plano Starter" },
  { company: "Five Star Ricos", code: "FIVESTARRICOSAGENCY", note: "Plano Agency" },
  { company: "Five Star Ricos", code: "FIVESTARRICOSGROWTH", note: "Plano Growth" },
  { company: "Five Star Ricos", code: "FIVESTARRICOSSTARTER", note: "Plano Starter" },
  { company: "FK Business Advice LLC", code: "FKBUSINESSADVICELLCAGENCY", note: "Plano Agency" },
  { company: "FK Business Advice LLC", code: "FKBUSINESSADVICELLCGROWTH", note: "Plano Growth" },
  { company: "FK Business Advice LLC", code: "FKBUSINESSADVIC1ARSTARTER", note: "Plano Starter" },
  { company: "Flavi Sant Anna", code: "FLAVISANTANNAAGENCY", note: "Plano Agency" },
  { company: "Flavi Sant Anna", code: "FLAVISANTANNAGROWTH", note: "Plano Growth" },
  { company: "Flavi Sant Anna", code: "FLAVISANTANNASTARTER", note: "Plano Starter" },
  { company: "Gabriel Ximenez's Account", code: "GABRIELXIMENEZSARSWAGENCY", note: "Plano Agency" },
  { company: "Gabriel Ximenez's Account", code: "GABRIELXIMENEZSARSWGROWTH", note: "Plano Growth" },
  { company: "Gabriel Ximenez's Account", code: "GABRIELXIMENEZSRSWSTARTER", note: "Plano Starter" },
  { company: "Gilmara", code: "GILMARAAGENCY", note: "Plano Agency" },
  { company: "Gilmara", code: "GILMARAGROWTH", note: "Plano Growth" },
  { company: "Gilmara", code: "GILMARASTARTER", note: "Plano Starter" },
  { company: "Growth Snapshot", code: "GROWTHSNAPSHOTAGENCY", note: "Plano Agency" },
  { company: "Growth Snapshot", code: "GROWTHSNAPSHOTGROWTH", note: "Plano Growth" },
  { company: "Growth Snapshot", code: "GROWTHSNAPSHOTSTARTER", note: "Plano Starter" },
  { company: "Growth Snapshot Clean Master v1", code: "GROWTHSNAPSHOTCL12MAGENCY", note: "Plano Agency" },
  { company: "Growth Snapshot Clean Master v1", code: "GROWTHSNAPSHOTCL12MGROWTH", note: "Plano Growth" },
  { company: "Growth Snapshot Clean Master v1", code: "GROWTHSNAPSHOTC12MSTARTER", note: "Plano Starter" },
  { company: "Guilherme Lappe", code: "GUILHERMELAPPEAGENCY", note: "Plano Agency" },
  { company: "Guilherme Lappe", code: "GUILHERMELAPPEGROWTH", note: "Plano Growth" },
  { company: "Guilherme Lappe", code: "GUILHERMELAPPESTARTER", note: "Plano Starter" },
  { company: "Gustavo Couto's Account", code: "GUSTAVOCOUTOSACC8UTAGENCY", note: "Plano Agency" },
  { company: "Gustavo Couto's Account", code: "GUSTAVOCOUTOSACC8UTGROWTH", note: "Plano Growth" },
  { company: "Gustavo Couto's Account", code: "GUSTAVOCOUTOSAC8UTSTARTER", note: "Plano Starter" },
  { company: "Haven Solutions", code: "HAVENSOLUTIONSAGENCY", note: "Plano Agency" },
  { company: "Haven Solutions", code: "HAVENSOLUTIONSGROWTH", note: "Plano Growth" },
  { company: "Haven Solutions", code: "HAVENSOLUTIONSSTARTER", note: "Plano Starter" },
  { company: "HELTON LEAL CARDOSO", code: "HELTONLEALCARDOSOAGENCY", note: "Plano Agency" },
  { company: "HELTON LEAL CARDOSO", code: "HELTONLEALCARDOSOGROWTH", note: "Plano Growth" },
  { company: "HELTON LEAL CARDOSO", code: "HELTONLEALCARDOSOSTARTER", note: "Plano Starter" },
  { company: "Heritage Group", code: "HERITAGEGROUPAGENCY", note: "Plano Agency" },
  { company: "Heritage Group", code: "HERITAGEGROUPGROWTH", note: "Plano Growth" },
  { company: "Heritage Group", code: "HERITAGEGROUPSTARTER", note: "Plano Starter" },
  { company: "High Up Financial", code: "HIGHUPFINANCIALAGENCY", note: "Plano Agency" },
  { company: "High Up Financial", code: "HIGHUPFINANCIALGROWTH", note: "Plano Growth" },
  { company: "High Up Financial", code: "HIGHUPFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Hope Financial Solutions", code: "HOPEFINANCIALSOLABMAGENCY", note: "Plano Agency" },
  { company: "Hope Financial Solutions", code: "HOPEFINANCIALSOLABMGROWTH", note: "Plano Growth" },
  { company: "Hope Financial Solutions", code: "HOPEFINANCIALSOABMSTARTER", note: "Plano Starter" },
  { company: "Ideal Business School", code: "IDEALBUSINESSSCHOOLAGENCY", note: "Plano Agency" },
  { company: "Ideal Business School", code: "IDEALBUSINESSSCHOOLGROWTH", note: "Plano Growth" },
  { company: "Ideal Business School", code: "IDEALBUSINESSSCMC3STARTER", note: "Plano Starter" },
  { company: "Ideal English School", code: "IDEALENGLISHSCHOOLAGENCY", note: "Plano Agency" },
  { company: "Ideal English School", code: "IDEALENGLISHSCHOOLGROWTH", note: "Plano Growth" },
  { company: "Ideal English School", code: "IDEALENGLISHSCHOOLSTARTER", note: "Plano Starter" },
  { company: "IGNORE", code: "IGNOREAGENCY", note: "Plano Agency" },
  { company: "IGNORE", code: "IGNOREGROWTH", note: "Plano Growth" },
  { company: "IGNORE", code: "IGNORESTARTER", note: "Plano Starter" },
  { company: "IMC Realty Group", code: "IMCREALTYGROUPAGENCY", note: "Plano Agency" },
  { company: "IMC Realty Group", code: "IMCREALTYGROUPGROWTH", note: "Plano Growth" },
  { company: "IMC Realty Group", code: "IMCREALTYGROUPSTARTER", note: "Plano Starter" },
  { company: "Imperium Life Protection", code: "IMPERIUMLIFEPROT1QEAGENCY", note: "Plano Agency" },
  { company: "Imperium Life Protection", code: "IMPERIUMLIFEPROT1QEGROWTH", note: "Plano Growth" },
  { company: "Imperium Life Protection", code: "IMPERIUMLIFEPRO1QESTARTER", note: "Plano Starter" },
  { company: "Ingrid Andre", code: "INGRIDANDREAGENCY", note: "Plano Agency" },
  { company: "Ingrid Andre", code: "INGRIDANDREGROWTH", note: "Plano Growth" },
  { company: "Ingrid Andre", code: "INGRIDANDRESTARTER", note: "Plano Starter" },
  { company: "Insurance Snapshot", code: "INSURANCESNAPSHOTAGENCY", note: "Plano Agency" },
  { company: "Insurance Snapshot", code: "INSURANCESNAPSHOTGROWTH", note: "Plano Growth" },
  { company: "Insurance Snapshot", code: "INSURANCESNAPSHOTSTARTER", note: "Plano Starter" },
  { company: "Iory Silva", code: "IORYSILVAAGENCY", note: "Plano Agency" },
  { company: "Iory Silva", code: "IORYSILVAGROWTH", note: "Plano Growth" },
  { company: "Iory Silva", code: "IORYSILVASTARTER", note: "Plano Starter" },
  { company: "Jaqueline Schoenrock", code: "JAQUELINESCHOENROCKAGENCY", note: "Plano Agency" },
  { company: "Jaqueline Schoenrock", code: "JAQUELINESCHOENROCKGROWTH", note: "Plano Growth" },
  { company: "Jaqueline Schoenrock", code: "JAQUELINESCHOEN1N3STARTER", note: "Plano Starter" },
  { company: "Jeane Thorpe", code: "JEANETHORPEAGENCY", note: "Plano Agency" },
  { company: "Jeane Thorpe", code: "JEANETHORPEGROWTH", note: "Plano Growth" },
  { company: "Jeane Thorpe", code: "JEANETHORPESTARTER", note: "Plano Starter" },
  { company: "JL Financial Strategies", code: "JLFINANCIALSTRATSDUAGENCY", note: "Plano Agency" },
  { company: "JL Financial Strategies", code: "JLFINANCIALSTRATSDUGROWTH", note: "Plano Growth" },
  { company: "JL Financial Strategies", code: "JLFINANCIALSTRASDUSTARTER", note: "Plano Starter" },
  { company: "John David", code: "JOHNDAVIDAGENCY", note: "Plano Agency" },
  { company: "John David", code: "JOHNDAVIDGROWTH", note: "Plano Growth" },
  { company: "John David", code: "JOHNDAVIDSTARTER", note: "Plano Starter" },
  { company: "John Langley", code: "JOHNLANGLEYAGENCY", note: "Plano Agency" },
  { company: "John Langley", code: "JOHNLANGLEYGROWTH", note: "Plano Growth" },
  { company: "John Langley", code: "JOHNLANGLEYSTARTER", note: "Plano Starter" },
  { company: "Jonathan Duque", code: "JONATHANDUQUEAGENCY", note: "Plano Agency" },
  { company: "Jonathan Duque", code: "JONATHANDUQUEGROWTH", note: "Plano Growth" },
  { company: "Jonathan Duque", code: "JONATHANDUQUESTARTER", note: "Plano Starter" },
  { company: "Ju E Lari", code: "JUELARIAGENCY", note: "Plano Agency" },
  { company: "Ju E Lari", code: "JUELARIGROWTH", note: "Plano Growth" },
  { company: "Ju E Lari", code: "JUELARISTARTER", note: "Plano Starter" },
  { company: "Jucelia Batista", code: "JUCELIABATISTAAGENCY", note: "Plano Agency" },
  { company: "Jucelia Batista", code: "JUCELIABATISTAGROWTH", note: "Plano Growth" },
  { company: "Jucelia Batista", code: "JUCELIABATISTASTARTER", note: "Plano Starter" },
  { company: "Juliana Pallesi's Account", code: "JULIANAPALLESISA1RIAGENCY", note: "Plano Agency" },
  { company: "Juliana Pallesi's Account", code: "JULIANAPALLESISA1RIGROWTH", note: "Plano Growth" },
  { company: "Juliana Pallesi's Account", code: "JULIANAPALLESIS1RISTARTER", note: "Plano Starter" },
  { company: "Jully Juvencio Saraiva", code: "JULLYJUVENCIOSARNZAAGENCY", note: "Plano Agency" },
  { company: "Jully Juvencio Saraiva", code: "JULLYJUVENCIOSARNZAGROWTH", note: "Plano Growth" },
  { company: "Jully Juvencio Saraiva", code: "JULLYJUVENCIOSANZASTARTER", note: "Plano Starter" },
  { company: "K Pires Financial", code: "KPIRESFINANCIALAGENCY", note: "Plano Agency" },
  { company: "K Pires Financial", code: "KPIRESFINANCIALGROWTH", note: "Plano Growth" },
  { company: "K Pires Financial", code: "KPIRESFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Katia Locher", code: "KATIALOCHERAGENCY", note: "Plano Agency" },
  { company: "Katia Locher", code: "KATIALOCHERGROWTH", note: "Plano Growth" },
  { company: "Katia Locher", code: "KATIALOCHERSTARTER", note: "Plano Starter" },
  { company: "kellen Silva", code: "KELLENSILVAAGENCY", note: "Plano Agency" },
  { company: "kellen Silva", code: "KELLENSILVAGROWTH", note: "Plano Growth" },
  { company: "kellen Silva", code: "KELLENSILVASTARTER", note: "Plano Starter" },
  { company: "Kingdom Financial", code: "KINGDOMFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Kingdom Financial", code: "KINGDOMFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Kingdom Financial", code: "KINGDOMFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Kingdom Sushi", code: "KINGDOMSUSHIAGENCY", note: "Plano Agency" },
  { company: "Kingdom Sushi", code: "KINGDOMSUSHIGROWTH", note: "Plano Growth" },
  { company: "Kingdom Sushi", code: "KINGDOMSUSHISTARTER", note: "Plano Starter" },
  { company: "Kingdom Wealth Finance", code: "KINGDOMWEALTHFIN13TAGENCY", note: "Plano Agency" },
  { company: "Kingdom Wealth Finance", code: "KINGDOMWEALTHFIN13TGROWTH", note: "Plano Growth" },
  { company: "Kingdom Wealth Finance", code: "KINGDOMWEALTHFI13TSTARTER", note: "Plano Starter" },
  { company: "Kore Group", code: "KOREGROUPAGENCY", note: "Plano Agency" },
  { company: "Kore Group", code: "KOREGROUPGROWTH", note: "Plano Growth" },
  { company: "Kore Group", code: "KOREGROUPSTARTER", note: "Plano Starter" },
  { company: "Laiza Estevão", code: "LAIZAESTEVAOAGENCY", note: "Plano Agency" },
  { company: "Laiza Estevão", code: "LAIZAESTEVAOGROWTH", note: "Plano Growth" },
  { company: "Laiza Estevão", code: "LAIZAESTEVAOSTARTER", note: "Plano Starter" },
  { company: "Lappe Financial Group", code: "LAPPEFINANCIALGROUPAGENCY", note: "Plano Agency" },
  { company: "Lappe Financial Group", code: "LAPPEFINANCIALGROUPGROWTH", note: "Plano Growth" },
  { company: "Lappe Financial Group", code: "LAPPEFINANCIALG18ESTARTER", note: "Plano Starter" },
  { company: "Leandro Pontoni's Account", code: "LEANDROPONTONISA1C8AGENCY", note: "Plano Agency" },
  { company: "Leandro Pontoni's Account", code: "LEANDROPONTONISA1C8GROWTH", note: "Plano Growth" },
  { company: "Leandro Pontoni's Account", code: "LEANDROPONTONIS1C8STARTER", note: "Plano Starter" },
  { company: "Legacy Agency", code: "LEGACYAGENCYAGENCY", note: "Plano Agency" },
  { company: "Legacy Agency", code: "LEGACYAGENCYGROWTH", note: "Plano Growth" },
  { company: "Legacy Agency", code: "LEGACYAGENCYSTARTER", note: "Plano Starter" },
  { company: "LIBERTY FINANCIAL", code: "LIBERTYFINANCIALAGENCY", note: "Plano Agency" },
  { company: "LIBERTY FINANCIAL", code: "LIBERTYFINANCIALGROWTH", note: "Plano Growth" },
  { company: "LIBERTY FINANCIAL", code: "LIBERTYFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Life Changers", code: "LIFECHANGERSAGENCY", note: "Plano Agency" },
  { company: "Life Changers", code: "LIFECHANGERSGROWTH", note: "Plano Growth" },
  { company: "Life Changers", code: "LIFECHANGERSSTARTER", note: "Plano Starter" },
  { company: "Lifeskeep", code: "LIFESKEEPAGENCY", note: "Plano Agency" },
  { company: "Lifeskeep", code: "LIFESKEEPGROWTH", note: "Plano Growth" },
  { company: "Lifeskeep", code: "LIFESKEEPSTARTER", note: "Plano Starter" },
  { company: "Livia Serpa's Account", code: "LIVIASERPASACCOUNTAGENCY", note: "Plano Agency" },
  { company: "Livia Serpa's Account", code: "LIVIASERPASACCOUNTGROWTH", note: "Plano Growth" },
  { company: "Livia Serpa's Account", code: "LIVIASERPASACCOUNTSTARTER", note: "Plano Starter" },
  { company: "Lucas Bandeira", code: "LUCASBANDEIRAAGENCY", note: "Plano Agency" },
  { company: "Lucas Bandeira", code: "LUCASBANDEIRAGROWTH", note: "Plano Growth" },
  { company: "Lucas Bandeira", code: "LUCASBANDEIRASTARTER", note: "Plano Starter" },
  { company: "Lunara Araujo", code: "LUNARAARAUJOAGENCY", note: "Plano Agency" },
  { company: "Lunara Araujo", code: "LUNARAARAUJOGROWTH", note: "Plano Growth" },
  { company: "Lunara Araujo", code: "LUNARAARAUJOSTARTER", note: "Plano Starter" },
  { company: "Magnet Money", code: "MAGNETMONEYAGENCY", note: "Plano Agency" },
  { company: "Magnet Money", code: "MAGNETMONEYGROWTH", note: "Plano Growth" },
  { company: "Magnet Money", code: "MAGNETMONEYSTARTER", note: "Plano Starter" },
  { company: "MAGNUM AGENCY", code: "MAGNUMAGENCYAGENCY", note: "Plano Agency" },
  { company: "MAGNUM AGENCY", code: "MAGNUMAGENCYGROWTH", note: "Plano Growth" },
  { company: "MAGNUM AGENCY", code: "MAGNUMAGENCYSTARTER", note: "Plano Starter" },
  { company: "Manual Call Snapshot", code: "MANUALCALLSNAPSHOTAGENCY", note: "Plano Agency" },
  { company: "Manual Call Snapshot", code: "MANUALCALLSNAPSHOTGROWTH", note: "Plano Growth" },
  { company: "Manual Call Snapshot", code: "MANUALCALLSNAPSHOTSTARTER", note: "Plano Starter" },
  { company: "Manuela Garcia Santos's Account", code: "MANUELAGARCIASANRMUAGENCY", note: "Plano Agency" },
  { company: "Manuela Garcia Santos's Account", code: "MANUELAGARCIASANRMUGROWTH", note: "Plano Growth" },
  { company: "Manuela Garcia Santos's Account", code: "MANUELAGARCIASARMUSTARTER", note: "Plano Starter" },
  { company: "Marcus Garcia", code: "MARCUSGARCIAAGENCY", note: "Plano Agency" },
  { company: "Marcus Garcia", code: "MARCUSGARCIAGROWTH", note: "Plano Growth" },
  { company: "Marcus Garcia", code: "MARCUSGARCIASTARTER", note: "Plano Starter" },
  { company: "Mariana Tambelini", code: "MARIANATAMBELINIAGENCY", note: "Plano Agency" },
  { company: "Mariana Tambelini", code: "MARIANATAMBELINIGROWTH", note: "Plano Growth" },
  { company: "Mariana Tambelini", code: "MARIANATAMBELINISTARTER", note: "Plano Starter" },
  { company: "Marina's Personal Account", code: "MARINASPERSONALANX2AGENCY", note: "Plano Agency" },
  { company: "Marina's Personal Account", code: "MARINASPERSONALANX2GROWTH", note: "Plano Growth" },
  { company: "Marina's Personal Account", code: "MARINASPERSONALNX2STARTER", note: "Plano Starter" },
  { company: "Marina's Support Account", code: "MARINASSUPPORTACALCAGENCY", note: "Plano Agency" },
  { company: "Marina's Support Account", code: "MARINASSUPPORTACALCGROWTH", note: "Plano Growth" },
  { company: "Marina's Support Account", code: "MARINASSUPPORTAALCSTARTER", note: "Plano Starter" },
  { company: "MD GROUP FINANCIAL", code: "MDGROUPFINANCIALAGENCY", note: "Plano Agency" },
  { company: "MD GROUP FINANCIAL", code: "MDGROUPFINANCIALGROWTH", note: "Plano Growth" },
  { company: "MD GROUP FINANCIAL", code: "MDGROUPFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Melina Wiebusch", code: "MELINAWIEBUSCHAGENCY", note: "Plano Agency" },
  { company: "Melina Wiebusch", code: "MELINAWIEBUSCHGROWTH", note: "Plano Growth" },
  { company: "Melina Wiebusch", code: "MELINAWIEBUSCHSTARTER", note: "Plano Starter" },
  { company: "Milionários", code: "MILIONARIOSAGENCY", note: "Plano Agency" },
  { company: "Milionários", code: "MILIONARIOSGROWTH", note: "Plano Growth" },
  { company: "Milionários", code: "MILIONARIOSSTARTER", note: "Plano Starter" },
  { company: "Milton De Abreu's Account", code: "MILTONDEABREUSACVVCAGENCY", note: "Plano Agency" },
  { company: "Milton De Abreu's Account", code: "MILTONDEABREUSACVVCGROWTH", note: "Plano Growth" },
  { company: "Milton De Abreu's Account", code: "MILTONDEABREUSAVVCSTARTER", note: "Plano Starter" },
  { company: "Mirolis Financial", code: "MIROLISFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Mirolis Financial", code: "MIROLISFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Mirolis Financial", code: "MIROLISFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Mission", code: "MISSIONAGENCY", note: "Plano Agency" },
  { company: "Mission", code: "MISSIONGROWTH", note: "Plano Growth" },
  { company: "Mission", code: "MISSIONSTARTER", note: "Plano Starter" },
  { company: "Money 4 Life", code: "MONEY4LIFEAGENCY", note: "Plano Agency" },
  { company: "Money 4 Life", code: "MONEY4LIFEGROWTH", note: "Plano Growth" },
  { company: "Money 4 Life", code: "MONEY4LIFESTARTER", note: "Plano Starter" },
  { company: "Money 4 Life USA", code: "MONEY4LIFEUSAAGENCY", note: "Plano Agency" },
  { company: "Money 4 Life USA", code: "MONEY4LIFEUSAGROWTH", note: "Plano Growth" },
  { company: "Money 4 Life USA", code: "MONEY4LIFEUSASTARTER", note: "Plano Starter" },
  { company: "Money Growth Financial", code: "MONEYGROWTHFINAN1RAAGENCY", note: "Plano Agency" },
  { company: "Money Growth Financial", code: "MONEYGROWTHFINAN1RAGROWTH", note: "Plano Growth" },
  { company: "Money Growth Financial", code: "MONEYGROWTHFINA1RASTARTER", note: "Plano Starter" },
  { company: "Money Masters", code: "MONEYMASTERSAGENCY", note: "Plano Agency" },
  { company: "Money Masters", code: "MONEYMASTERSGROWTH", note: "Plano Growth" },
  { company: "Money Masters", code: "MONEYMASTERSSTARTER", note: "Plano Starter" },
  { company: "Money Matters", code: "MONEYMATTERSAGENCY", note: "Plano Agency" },
  { company: "Money Matters", code: "MONEYMATTERSGROWTH", note: "Plano Growth" },
  { company: "Money Matters", code: "MONEYMATTERSSTARTER", note: "Plano Starter" },
  { company: "MoneySource Management", code: "MONEYSOURCEMANAGZA8AGENCY", note: "Plano Agency" },
  { company: "MoneySource Management", code: "MONEYSOURCEMANAGZA8GROWTH", note: "Plano Growth" },
  { company: "MoneySource Management", code: "MONEYSOURCEMANAZA8STARTER", note: "Plano Starter" },
  { company: "Monica Gasparetto Consulting Services", code: "MONICAGASPARETTOSN4AGENCY", note: "Plano Agency" },
  { company: "Monica Gasparetto Consulting Services", code: "MONICAGASPARETTOSN4GROWTH", note: "Plano Growth" },
  { company: "Monica Gasparetto Consulting Services", code: "MONICAGASPARETTSN4STARTER", note: "Plano Starter" },
  { company: "MOURA CFO", code: "MOURACFOAGENCY", note: "Plano Agency" },
  { company: "MOURA CFO", code: "MOURACFOGROWTH", note: "Plano Growth" },
  { company: "MOURA CFO", code: "MOURACFOSTARTER", note: "Plano Starter" },
  { company: "Mynke", code: "MYNKEAGENCY", note: "Plano Agency" },
  { company: "Mynke", code: "MYNKEGROWTH", note: "Plano Growth" },
  { company: "Mynke", code: "MYNKESTARTER", note: "Plano Starter" },
  { company: "Neway Pools FL", code: "NEWAYPOOLSFLAGENCY", note: "Plano Agency" },
  { company: "Neway Pools FL", code: "NEWAYPOOLSFLGROWTH", note: "Plano Growth" },
  { company: "Neway Pools FL", code: "NEWAYPOOLSFLSTARTER", note: "Plano Starter" },
  { company: "Neway Pools.", code: "NEWAYPOOLSAGENCY", note: "Plano Agency" },
  { company: "Neway Pools.", code: "NEWAYPOOLSGROWTH", note: "Plano Growth" },
  { company: "Neway Pools.", code: "NEWAYPOOLSSTARTER", note: "Plano Starter" },
  { company: "Next Level Finances", code: "NEXTLEVELFINANCESAGENCY", note: "Plano Agency" },
  { company: "Next Level Finances", code: "NEXTLEVELFINANCESGROWTH", note: "Plano Growth" },
  { company: "Next Level Finances", code: "NEXTLEVELFINANCESSTARTER", note: "Plano Starter" },
  { company: "Nexus", code: "NEXUSAGENCY", note: "Plano Agency" },
  { company: "Nexus", code: "NEXUSGROWTH", note: "Plano Growth" },
  { company: "Nexus", code: "NEXUSSTARTER", note: "Plano Starter" },
  { company: "NL Aquece Numero", code: "NLAQUECENUMEROAGENCY", note: "Plano Agency" },
  { company: "NL Aquece Numero", code: "NLAQUECENUMEROGROWTH", note: "Plano Growth" },
  { company: "NL Aquece Numero", code: "NLAQUECENUMEROSTARTER", note: "Plano Starter" },
  { company: "NSISUCESSO", code: "NSISUCESSOAGENCY", note: "Plano Agency" },
  { company: "NSISUCESSO", code: "NSISUCESSOGROWTH", note: "Plano Growth" },
  { company: "NSISUCESSO", code: "NSISUCESSOSTARTER", note: "Plano Starter" },
  { company: "Nuvo Capital", code: "NUVOCAPITALAGENCY", note: "Plano Agency" },
  { company: "Nuvo Capital", code: "NUVOCAPITALGROWTH", note: "Plano Growth" },
  { company: "Nuvo Capital", code: "NUVOCAPITALSTARTER", note: "Plano Starter" },
  { company: "OkFOREVER", code: "OKFOREVERAGENCY", note: "Plano Agency" },
  { company: "OkFOREVER", code: "OKFOREVERGROWTH", note: "Plano Growth" },
  { company: "OkFOREVER", code: "OKFOREVERSTARTER", note: "Plano Starter" },
  { company: "Omnys", code: "OMNYSAGENCY", note: "Plano Agency" },
  { company: "Omnys", code: "OMNYSGROWTH", note: "Plano Growth" },
  { company: "Omnys", code: "OMNYSSTARTER", note: "Plano Starter" },
  { company: "Onofre Arruda", code: "ONOFREARRUDAAGENCY", note: "Plano Agency" },
  { company: "Onofre Arruda", code: "ONOFREARRUDAGROWTH", note: "Plano Growth" },
  { company: "Onofre Arruda", code: "ONOFREARRUDASTARTER", note: "Plano Starter" },
  { company: "Onofre Linhares", code: "ONOFRELINHARESAGENCY", note: "Plano Agency" },
  { company: "Onofre Linhares", code: "ONOFRELINHARESGROWTH", note: "Plano Growth" },
  { company: "Onofre Linhares", code: "ONOFRELINHARESSTARTER", note: "Plano Starter" },
  { company: "Opta Finance", code: "OPTAFINANCEAGENCY", note: "Plano Agency" },
  { company: "Opta Finance", code: "OPTAFINANCEGROWTH", note: "Plano Growth" },
  { company: "Opta Finance", code: "OPTAFINANCESTARTER", note: "Plano Starter" },
  { company: "Orlux Rental", code: "ORLUXRENTALAGENCY", note: "Plano Agency" },
  { company: "Orlux Rental", code: "ORLUXRENTALGROWTH", note: "Plano Growth" },
  { company: "Orlux Rental", code: "ORLUXRENTALSTARTER", note: "Plano Starter" },
  { company: "P3 Financial", code: "P3FINANCIALAGENCY", note: "Plano Agency" },
  { company: "P3 Financial", code: "P3FINANCIALGROWTH", note: "Plano Growth" },
  { company: "P3 Financial", code: "P3FINANCIALSTARTER", note: "Plano Starter" },
  { company: "Parterns Team", code: "PARTERNSTEAMAGENCY", note: "Plano Agency" },
  { company: "Parterns Team", code: "PARTERNSTEAMGROWTH", note: "Plano Growth" },
  { company: "Parterns Team", code: "PARTERNSTEAMSTARTER", note: "Plano Starter" },
  { company: "Paulo Garcia", code: "PAULOGARCIAAGENCY", note: "Plano Agency" },
  { company: "Paulo Garcia", code: "PAULOGARCIAGROWTH", note: "Plano Growth" },
  { company: "Paulo Garcia", code: "PAULOGARCIASTARTER", note: "Plano Starter" },
  { company: "Pedro Poleza's Account", code: "PEDROPOLEZASACCOUNTAGENCY", note: "Plano Agency" },
  { company: "Pedro Poleza's Account", code: "PEDROPOLEZASACCOUNTGROWTH", note: "Plano Growth" },
  { company: "Pedro Poleza's Account", code: "PEDROPOLEZASACC1Z0STARTER", note: "Plano Starter" },
  { company: "Pedro Polezaa", code: "PEDROPOLEZAAAGENCY", note: "Plano Agency" },
  { company: "Pedro Polezaa", code: "PEDROPOLEZAAGROWTH", note: "Plano Growth" },
  { company: "Pedro Polezaa", code: "PEDROPOLEZAASTARTER", note: "Plano Starter" },
  { company: "PGI 2", code: "PGI2AGENCY", note: "Plano Agency" },
  { company: "PGI 2", code: "PGI2GROWTH", note: "Plano Growth" },
  { company: "PGI 2", code: "PGI2STARTER", note: "Plano Starter" },
  { company: "PGI Financial Group", code: "PGIFINANCIALGROUPAGENCY", note: "Plano Agency" },
  { company: "PGI Financial Group", code: "PGIFINANCIALGROUPGROWTH", note: "Plano Growth" },
  { company: "PGI Financial Group", code: "PGIFINANCIALGROUPSTARTER", note: "Plano Starter" },
  { company: "pi Legacy", code: "PILEGACYAGENCY", note: "Plano Agency" },
  { company: "pi Legacy", code: "PILEGACYGROWTH", note: "Plano Growth" },
  { company: "pi Legacy", code: "PILEGACYSTARTER", note: "Plano Starter" },
  { company: "Pontoni Financial Corp", code: "PONTONIFINANCIAL1CVAGENCY", note: "Plano Agency" },
  { company: "Pontoni Financial Corp", code: "PONTONIFINANCIAL1CVGROWTH", note: "Plano Growth" },
  { company: "Pontoni Financial Corp", code: "PONTONIFINANCIA1CVSTARTER", note: "Plano Starter" },
  { company: "Precious Planning", code: "PRECIOUSPLANNINGAGENCY", note: "Plano Agency" },
  { company: "Precious Planning", code: "PRECIOUSPLANNINGGROWTH", note: "Plano Growth" },
  { company: "Precious Planning", code: "PRECIOUSPLANNINGSTARTER", note: "Plano Starter" },
  { company: "Prime Immigration Office", code: "PRIMEIMMIGRATIONFR0AGENCY", note: "Plano Agency" },
  { company: "Prime Immigration Office", code: "PRIMEIMMIGRATIONFR0GROWTH", note: "Plano Growth" },
  { company: "Prime Immigration Office", code: "PRIMEIMMIGRATIOFR0STARTER", note: "Plano Starter" },
  { company: "Priscilla Lacerda", code: "PRISCILLALACERDAAGENCY", note: "Plano Agency" },
  { company: "Priscilla Lacerda", code: "PRISCILLALACERDAGROWTH", note: "Plano Growth" },
  { company: "Priscilla Lacerda", code: "PRISCILLALACERDASTARTER", note: "Plano Starter" },
  { company: "Priscilla Lacerda's Account", code: "PRISCILLALACERDA1AYAGENCY", note: "Plano Agency" },
  { company: "Priscilla Lacerda's Account", code: "PRISCILLALACERDA1AYGROWTH", note: "Plano Growth" },
  { company: "Priscilla Lacerda's Account", code: "PRISCILLALACERD1AYSTARTER", note: "Plano Starter" },
  { company: "Prosperar USA", code: "PROSPERARUSAAGENCY", note: "Plano Agency" },
  { company: "Prosperar USA", code: "PROSPERARUSAGROWTH", note: "Plano Growth" },
  { company: "Prosperar USA", code: "PROSPERARUSASTARTER", note: "Plano Starter" },
  { company: "Prosperlife Advisors", code: "PROSPERLIFEADVISORSAGENCY", note: "Plano Agency" },
  { company: "Prosperlife Advisors", code: "PROSPERLIFEADVISORSGROWTH", note: "Plano Growth" },
  { company: "Prosperlife Advisors", code: "PROSPERLIFEADVI115STARTER", note: "Plano Starter" },
  { company: "Quantum Evolution Corp", code: "QUANTUMEVOLUTION16MAGENCY", note: "Plano Agency" },
  { company: "Quantum Evolution Corp", code: "QUANTUMEVOLUTION16MGROWTH", note: "Plano Growth" },
  { company: "Quantum Evolution Corp", code: "QUANTUMEVOLUTIO16MSTARTER", note: "Plano Starter" },
  { company: "Rafael de Paula", code: "RAFAELDEPAULAAGENCY", note: "Plano Agency" },
  { company: "Rafael de Paula", code: "RAFAELDEPAULAGROWTH", note: "Plano Growth" },
  { company: "Rafael de Paula", code: "RAFAELDEPAULASTARTER", note: "Plano Starter" },
  { company: "Renata Luque Agente Financeira", code: "RENATALUQUEAGENTA9XAGENCY", note: "Plano Agency" },
  { company: "Renata Luque Agente Financeira", code: "RENATALUQUEAGENTA9XGROWTH", note: "Plano Growth" },
  { company: "Renata Luque Agente Financeira", code: "RENATALUQUEAGENA9XSTARTER", note: "Plano Starter" },
  { company: "Renato Testing Account", code: "RENATOTESTINGACC3TCAGENCY", note: "Plano Agency" },
  { company: "Renato Testing Account", code: "RENATOTESTINGACC3TCGROWTH", note: "Plano Growth" },
  { company: "Renato Testing Account", code: "RENATOTESTINGAC3TCSTARTER", note: "Plano Starter" },
  { company: "Rico$", code: "RICOAGENCY", note: "Plano Agency" },
  { company: "Rico$", code: "RICOGROWTH", note: "Plano Growth" },
  { company: "Rico$", code: "RICOSTARTER", note: "Plano Starter" },
  { company: "Riqueza na América", code: "RIQUEZANAAMERICAAGENCY", note: "Plano Agency" },
  { company: "Riqueza na América", code: "RIQUEZANAAMERICAGROWTH", note: "Plano Growth" },
  { company: "Riqueza na América", code: "RIQUEZANAAMERICASTARTER", note: "Plano Starter" },
  { company: "Rj Usa Money Management", code: "RJUSAMONEYMANAGEQ4CAGENCY", note: "Plano Agency" },
  { company: "Rj Usa Money Management", code: "RJUSAMONEYMANAGEQ4CGROWTH", note: "Plano Growth" },
  { company: "Rj Usa Money Management", code: "RJUSAMONEYMANAGQ4CSTARTER", note: "Plano Starter" },
  { company: "RM STRONG FINANCIAL", code: "RMSTRONGFINANCIALAGENCY", note: "Plano Agency" },
  { company: "RM STRONG FINANCIAL", code: "RMSTRONGFINANCIALGROWTH", note: "Plano Growth" },
  { company: "RM STRONG FINANCIAL", code: "RMSTRONGFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Ronaldo De Oliveira", code: "RONALDODEOLIVEIRAAGENCY", note: "Plano Agency" },
  { company: "Ronaldo De Oliveira", code: "RONALDODEOLIVEIRAGROWTH", note: "Plano Growth" },
  { company: "Ronaldo De Oliveira", code: "RONALDODEOLIVEIRASTARTER", note: "Plano Starter" },
  { company: "RS ACCOUNTING AND TAX", code: "RSACCOUNTINGANDTAXAGENCY", note: "Plano Agency" },
  { company: "RS ACCOUNTING AND TAX", code: "RSACCOUNTINGANDTAXGROWTH", note: "Plano Growth" },
  { company: "RS ACCOUNTING AND TAX", code: "RSACCOUNTINGANDTAXSTARTER", note: "Plano Starter" },
  { company: "Sabrina Caldas", code: "SABRINACALDASAGENCY", note: "Plano Agency" },
  { company: "Sabrina Caldas", code: "SABRINACALDASGROWTH", note: "Plano Growth" },
  { company: "Sabrina Caldas", code: "SABRINACALDASSTARTER", note: "Plano Starter" },
  { company: "Safe Life Financial", code: "SAFELIFEFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Safe Life Financial", code: "SAFELIFEFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Safe Life Financial", code: "SAFELIFEFINANCIALSTARTER", note: "Plano Starter" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "SCALESNAPSHOTLEG1UZAGENCY", note: "Plano Agency" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "SCALESNAPSHOTLEG1UZGROWTH", note: "Plano Growth" },
  { company: "Scale Snapshot (LEGADO - não usar)", code: "SCALESNAPSHOTLE1UZSTARTER", note: "Plano Starter" },
  { company: "Silvia Mendes", code: "SILVIAMENDESAGENCY", note: "Plano Agency" },
  { company: "Silvia Mendes", code: "SILVIAMENDESGROWTH", note: "Plano Growth" },
  { company: "Silvia Mendes", code: "SILVIAMENDESSTARTER", note: "Plano Starter" },
  { company: "SJ Smart Financial LLC", code: "SJSMARTFINANCIALLLCAGENCY", note: "Plano Agency" },
  { company: "SJ Smart Financial LLC", code: "SJSMARTFINANCIALLLCGROWTH", note: "Plano Growth" },
  { company: "SJ Smart Financial LLC", code: "SJSMARTFINANCIA1W7STARTER", note: "Plano Starter" },
  { company: "Soneko Colchões", code: "SONEKOCOLCHOESAGENCY", note: "Plano Agency" },
  { company: "Soneko Colchões", code: "SONEKOCOLCHOESGROWTH", note: "Plano Growth" },
  { company: "Soneko Colchões", code: "SONEKOCOLCHOESSTARTER", note: "Plano Starter" },
  { company: "Soraia Close", code: "SORAIACLOSEAGENCY", note: "Plano Agency" },
  { company: "Soraia Close", code: "SORAIACLOSEGROWTH", note: "Plano Growth" },
  { company: "Soraia Close", code: "SORAIACLOSESTARTER", note: "Plano Starter" },
  { company: "South Florida Maids Pro", code: "SOUTHFLORIDAMAID1JIAGENCY", note: "Plano Agency" },
  { company: "South Florida Maids Pro", code: "SOUTHFLORIDAMAID1JIGROWTH", note: "Plano Growth" },
  { company: "South Florida Maids Pro", code: "SOUTHFLORIDAMAI1JISTARTER", note: "Plano Starter" },
  { company: "Spark Demo Teste CERTO", code: "SPARKDEMOTESTECERTOAGENCY", note: "Plano Agency" },
  { company: "Spark Demo Teste CERTO", code: "SPARKDEMOTESTECERTOGROWTH", note: "Plano Growth" },
  { company: "Spark Demo Teste CERTO", code: "SPARKDEMOTESTECP1VSTARTER", note: "Plano Starter" },
  { company: "Spark Leads", code: "SPARKLEADSAGENCY", note: "Plano Agency" },
  { company: "Spark Leads", code: "SPARKLEADSGROWTH", note: "Plano Growth" },
  { company: "Spark Leads", code: "SPARKLEADSSTARTER", note: "Plano Starter" },
  { company: "Spark Leadss", code: "SPARKLEADSSAGENCY", note: "Plano Agency" },
  { company: "Spark Leadss", code: "SPARKLEADSSGROWTH", note: "Plano Growth" },
  { company: "Spark Leadss", code: "SPARKLEADSSSTARTER", note: "Plano Starter" },
  { company: "Spark Leadss FT", code: "SPARKLEADSSFTAGENCY", note: "Plano Agency" },
  { company: "Spark Leadss FT", code: "SPARKLEADSSFTGROWTH", note: "Plano Growth" },
  { company: "Spark Leadss FT", code: "SPARKLEADSSFTSTARTER", note: "Plano Starter" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "SPARKSCALEV1CLEAJNWAGENCY", note: "Plano Agency" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "SPARKSCALEV1CLEAJNWGROWTH", note: "Plano Growth" },
  { company: "Spark Scale v1 — CLEAN MASTER", code: "SPARKSCALEV1CLEJNWSTARTER", note: "Plano Starter" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "SPARKSTARTERV1CL1YUAGENCY", note: "Plano Agency" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "SPARKSTARTERV1CL1YUGROWTH", note: "Plano Growth" },
  { company: "Spark Starter v1 — CLEAN MASTER", code: "SPARKSTARTERV1C1YUSTARTER", note: "Plano Starter" },
  { company: "SparkBot", code: "SPARKBOTAGENCY", note: "Plano Agency" },
  { company: "SparkBot", code: "SPARKBOTGROWTH", note: "Plano Growth" },
  { company: "SparkBot", code: "SPARKBOTSTARTER", note: "Plano Starter" },
  { company: "SparkGo", code: "SPARKGOAGENCY", note: "Plano Agency" },
  { company: "SparkGo", code: "SPARKGOGROWTH", note: "Plano Growth" },
  { company: "SparkGo", code: "SPARKGOSTARTER", note: "Plano Starter" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "STARTERSNAPSHOTL55FAGENCY", note: "Plano Agency" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "STARTERSNAPSHOTL55FGROWTH", note: "Plano Growth" },
  { company: "Starter Snapshot (LEGADO - não usar)", code: "STARTERSNAPSHOT55FSTARTER", note: "Plano Starter" },
  { company: "Staziaki Financial Solutions", code: "STAZIAKIFINANCIA1SJAGENCY", note: "Plano Agency" },
  { company: "Staziaki Financial Solutions", code: "STAZIAKIFINANCIA1SJGROWTH", note: "Plano Growth" },
  { company: "Staziaki Financial Solutions", code: "STAZIAKIFINANCI1SJSTARTER", note: "Plano Starter" },
  { company: "Summit Life Financial", code: "SUMMITLIFEFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Summit Life Financial", code: "SUMMITLIFEFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Summit Life Financial", code: "SUMMITLIFEFINAN16QSTARTER", note: "Plano Starter" },
  { company: "Tatyane Rodrigues Soprani", code: "TATYANERODRIGUES1OEAGENCY", note: "Plano Agency" },
  { company: "Tatyane Rodrigues Soprani", code: "TATYANERODRIGUES1OEGROWTH", note: "Plano Growth" },
  { company: "Tatyane Rodrigues Soprani", code: "TATYANERODRIGUE1OESTARTER", note: "Plano Starter" },
  { company: "Tchovas Agency", code: "TCHOVASAGENCYAGENCY", note: "Plano Agency" },
  { company: "Tchovas Agency", code: "TCHOVASAGENCYGROWTH", note: "Plano Growth" },
  { company: "Tchovas Agency", code: "TCHOVASAGENCYSTARTER", note: "Plano Starter" },
  { company: "Team De Elite", code: "TEAMDEELITEAGENCY", note: "Plano Agency" },
  { company: "Team De Elite", code: "TEAMDEELITEGROWTH", note: "Plano Growth" },
  { company: "Team De Elite", code: "TEAMDEELITESTARTER", note: "Plano Starter" },
  { company: "Teste May 16", code: "TESTEMAY16AGENCY", note: "Plano Agency" },
  { company: "Teste May 16", code: "TESTEMAY16GROWTH", note: "Plano Growth" },
  { company: "Teste May 16", code: "TESTEMAY16STARTER", note: "Plano Starter" },
  { company: "TESTE PEDRO BO", code: "TESTEPEDROBOAGENCY", note: "Plano Agency" },
  { company: "TESTE PEDRO BO", code: "TESTEPEDROBOGROWTH", note: "Plano Growth" },
  { company: "TESTE PEDRO BO", code: "TESTEPEDROBOSTARTER", note: "Plano Starter" },
  { company: "The Rich Life Guide", code: "THERICHLIFEGUIDEAGENCY", note: "Plano Agency" },
  { company: "The Rich Life Guide", code: "THERICHLIFEGUIDEGROWTH", note: "Plano Growth" },
  { company: "The Rich Life Guide", code: "THERICHLIFEGUIDESTARTER", note: "Plano Starter" },
  { company: "Thiago Rabaneda", code: "THIAGORABANEDAAGENCY", note: "Plano Agency" },
  { company: "Thiago Rabaneda", code: "THIAGORABANEDAGROWTH", note: "Plano Growth" },
  { company: "Thiago Rabaneda", code: "THIAGORABANEDASTARTER", note: "Plano Starter" },
  { company: "Thiago Rechi - Agente Financeiro", code: "THIAGORECHIAGENTIT9AGENCY", note: "Plano Agency" },
  { company: "Thiago Rechi - Agente Financeiro", code: "THIAGORECHIAGENTIT9GROWTH", note: "Plano Growth" },
  { company: "Thiago Rechi - Agente Financeiro", code: "THIAGORECHIAGENIT9STARTER", note: "Plano Starter" },
  { company: "Time Dos Prósperos", code: "TIMEDOSPROSPEROSAGENCY", note: "Plano Agency" },
  { company: "Time Dos Prósperos", code: "TIMEDOSPROSPEROSGROWTH", note: "Plano Growth" },
  { company: "Time Dos Prósperos", code: "TIMEDOSPROSPEROSSTARTER", note: "Plano Starter" },
  { company: "Titans Agency", code: "TITANSAGENCYAGENCY", note: "Plano Agency" },
  { company: "Titans Agency", code: "TITANSAGENCYGROWTH", note: "Plano Growth" },
  { company: "Titans Agency", code: "TITANSAGENCYSTARTER", note: "Plano Starter" },
  { company: "U&M Financial", code: "UMFINANCIALAGENCY", note: "Plano Agency" },
  { company: "U&M Financial", code: "UMFINANCIALGROWTH", note: "Plano Growth" },
  { company: "U&M Financial", code: "UMFINANCIALSTARTER", note: "Plano Starter" },
  { company: "U&M Financial Solutions", code: "UMFINANCIALSOLUTJ4AAGENCY", note: "Plano Agency" },
  { company: "U&M Financial Solutions", code: "UMFINANCIALSOLUTJ4AGROWTH", note: "Plano Growth" },
  { company: "U&M Financial Solutions", code: "UMFINANCIALSOLUJ4ASTARTER", note: "Plano Starter" },
  { company: "V&F FINANCIAL SERVICES", code: "VFFINANCIALSERVICESAGENCY", note: "Plano Agency" },
  { company: "V&F FINANCIAL SERVICES", code: "VFFINANCIALSERVICESGROWTH", note: "Plano Growth" },
  { company: "V&F FINANCIAL SERVICES", code: "VFFINANCIALSERV1D3STARTER", note: "Plano Starter" },
  { company: "ValeriaSartori", code: "VALERIASARTORIAGENCY", note: "Plano Agency" },
  { company: "ValeriaSartori", code: "VALERIASARTORIGROWTH", note: "Plano Growth" },
  { company: "ValeriaSartori", code: "VALERIASARTORISTARTER", note: "Plano Starter" },
  { company: "Vasti Rodrigues", code: "VASTIRODRIGUESAGENCY", note: "Plano Agency" },
  { company: "Vasti Rodrigues", code: "VASTIRODRIGUESGROWTH", note: "Plano Growth" },
  { company: "Vasti Rodrigues", code: "VASTIRODRIGUESSTARTER", note: "Plano Starter" },
  { company: "Victor Costa", code: "VICTORCOSTAAGENCY", note: "Plano Agency" },
  { company: "Victor Costa", code: "VICTORCOSTAGROWTH", note: "Plano Growth" },
  { company: "Victor Costa", code: "VICTORCOSTASTARTER", note: "Plano Starter" },
  { company: "Vida Bela", code: "VIDABELAAGENCY", note: "Plano Agency" },
  { company: "Vida Bela", code: "VIDABELAGROWTH", note: "Plano Growth" },
  { company: "Vida Bela", code: "VIDABELASTARTER", note: "Plano Starter" },
  { company: "Vida Bela LLC", code: "VIDABELALLCAGENCY", note: "Plano Agency" },
  { company: "Vida Bela LLC", code: "VIDABELALLCGROWTH", note: "Plano Growth" },
  { company: "Vida Bela LLC", code: "VIDABELALLCSTARTER", note: "Plano Starter" },
  { company: "Vincit Capital", code: "VINCITCAPITALAGENCY", note: "Plano Agency" },
  { company: "Vincit Capital", code: "VINCITCAPITALGROWTH", note: "Plano Growth" },
  { company: "Vincit Capital", code: "VINCITCAPITALSTARTER", note: "Plano Starter" },
  { company: "Vinicius Mora's Account", code: "VINICIUSMORASACC5OAAGENCY", note: "Plano Agency" },
  { company: "Vinicius Mora's Account", code: "VINICIUSMORASACC5OAGROWTH", note: "Plano Growth" },
  { company: "Vinicius Mora's Account", code: "VINICIUSMORASAC5OASTARTER", note: "Plano Starter" },
  { company: "Vinicius Moraes", code: "VINICIUSMORAESAGENCY", note: "Plano Agency" },
  { company: "Vinicius Moraes", code: "VINICIUSMORAESGROWTH", note: "Plano Growth" },
  { company: "Vinicius Moraes", code: "VINICIUSMORAESSTARTER", note: "Plano Starter" },
  { company: "Vision Group", code: "VISIONGROUPAGENCY", note: "Plano Agency" },
  { company: "Vision Group", code: "VISIONGROUPGROWTH", note: "Plano Growth" },
  { company: "Vision Group", code: "VISIONGROUPSTARTER", note: "Plano Starter" },
  { company: "Vivian Osorio's Account", code: "VIVIANOSORIOSACCSB9AGENCY", note: "Plano Agency" },
  { company: "Vivian Osorio's Account", code: "VIVIANOSORIOSACCSB9GROWTH", note: "Plano Growth" },
  { company: "Vivian Osorio's Account", code: "VIVIANOSORIOSACSB9STARTER", note: "Plano Starter" },
  { company: "Viviane Goellner", code: "VIVIANEGOELLNERAGENCY", note: "Plano Agency" },
  { company: "Viviane Goellner", code: "VIVIANEGOELLNERGROWTH", note: "Plano Growth" },
  { company: "Viviane Goellner", code: "VIVIANEGOELLNERSTARTER", note: "Plano Starter" },
  { company: "Viviane Quinalha", code: "VIVIANEQUINALHAAGENCY", note: "Plano Agency" },
  { company: "Viviane Quinalha", code: "VIVIANEQUINALHAGROWTH", note: "Plano Growth" },
  { company: "Viviane Quinalha", code: "VIVIANEQUINALHASTARTER", note: "Plano Starter" },
  { company: "Viviane Rodrigues's Account", code: "VIVIANERODRIGUESUO0AGENCY", note: "Plano Agency" },
  { company: "Viviane Rodrigues's Account", code: "VIVIANERODRIGUESUO0GROWTH", note: "Plano Growth" },
  { company: "Viviane Rodrigues's Account", code: "VIVIANERODRIGUEUO0STARTER", note: "Plano Starter" },
  { company: "Wagner Witka's Account", code: "WAGNERWITKASACCOUNTAGENCY", note: "Plano Agency" },
  { company: "Wagner Witka's Account", code: "WAGNERWITKASACCOUNTGROWTH", note: "Plano Growth" },
  { company: "Wagner Witka's Account", code: "WAGNERWITKASACCF8CSTARTER", note: "Plano Starter" },
  { company: "WattsUpEnergy", code: "WATTSUPENERGYAGENCY", note: "Plano Agency" },
  { company: "WattsUpEnergy", code: "WATTSUPENERGYGROWTH", note: "Plano Growth" },
  { company: "WattsUpEnergy", code: "WATTSUPENERGYSTARTER", note: "Plano Starter" },
  { company: "Wise Wallet Financial", code: "WISEWALLETFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Wise Wallet Financial", code: "WISEWALLETFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Wise Wallet Financial", code: "WISEWALLETFINAN649STARTER", note: "Plano Starter" },
  { company: "Witka Financial", code: "WITKAFINANCIALAGENCY", note: "Plano Agency" },
  { company: "Witka Financial", code: "WITKAFINANCIALGROWTH", note: "Plano Growth" },
  { company: "Witka Financial", code: "WITKAFINANCIALSTARTER", note: "Plano Starter" },
  { company: "ZAP Guilherme", code: "ZAPGUILHERMEAGENCY", note: "Plano Agency" },
  { company: "ZAP Guilherme", code: "ZAPGUILHERMEGROWTH", note: "Plano Growth" },
  { company: "ZAP Guilherme", code: "ZAPGUILHERMESTARTER", note: "Plano Starter" },
  { company: "ZAPIER Testing Account", code: "ZAPIERTESTINGACCMJRAGENCY", note: "Plano Agency" },
  { company: "ZAPIER Testing Account", code: "ZAPIERTESTINGACCMJRGROWTH", note: "Plano Growth" },
  { company: "ZAPIER Testing Account", code: "ZAPIERTESTINGACMJRSTARTER", note: "Plano Starter" },
];
